// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/proto/application/application.proto

package applicationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "koloney-protos/v1/go/google/api"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApplicationStatus represents the overall status.
type ApplicationStatus int32

const (
	// The application status is unspecified.
	ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED ApplicationStatus = 0
	// The application is in draft mode.
	ApplicationStatus_APPLICATION_STATUS_DRAFT ApplicationStatus = 1
	// The application has been submitted.
	ApplicationStatus_APPLICATION_STATUS_SUBMITTED ApplicationStatus = 2
	// The application is under review.
	ApplicationStatus_APPLICATION_STATUS_UNDER_REVIEW ApplicationStatus = 3
	// The application is in the interviewing stage.
	ApplicationStatus_APPLICATION_STATUS_INTERVIEWING ApplicationStatus = 4
	// An offer has been extended.
	ApplicationStatus_APPLICATION_STATUS_OFFER_EXTENDED ApplicationStatus = 5
	// The application has been accepted.
	ApplicationStatus_APPLICATION_STATUS_ACCEPTED ApplicationStatus = 6
	// The application has been rejected.
	ApplicationStatus_APPLICATION_STATUS_REJECTED ApplicationStatus = 7
	// The application has been withdrawn.
	ApplicationStatus_APPLICATION_STATUS_WITHDRAWN ApplicationStatus = 8
)

// Enum value maps for ApplicationStatus.
var (
	ApplicationStatus_name = map[int32]string{
		0: "APPLICATION_STATUS_UNSPECIFIED",
		1: "APPLICATION_STATUS_DRAFT",
		2: "APPLICATION_STATUS_SUBMITTED",
		3: "APPLICATION_STATUS_UNDER_REVIEW",
		4: "APPLICATION_STATUS_INTERVIEWING",
		5: "APPLICATION_STATUS_OFFER_EXTENDED",
		6: "APPLICATION_STATUS_ACCEPTED",
		7: "APPLICATION_STATUS_REJECTED",
		8: "APPLICATION_STATUS_WITHDRAWN",
	}
	ApplicationStatus_value = map[string]int32{
		"APPLICATION_STATUS_UNSPECIFIED":    0,
		"APPLICATION_STATUS_DRAFT":          1,
		"APPLICATION_STATUS_SUBMITTED":      2,
		"APPLICATION_STATUS_UNDER_REVIEW":   3,
		"APPLICATION_STATUS_INTERVIEWING":   4,
		"APPLICATION_STATUS_OFFER_EXTENDED": 5,
		"APPLICATION_STATUS_ACCEPTED":       6,
		"APPLICATION_STATUS_REJECTED":       7,
		"APPLICATION_STATUS_WITHDRAWN":      8,
	}
)

func (x ApplicationStatus) Enum() *ApplicationStatus {
	p := new(ApplicationStatus)
	*p = x
	return p
}

func (x ApplicationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_application_application_proto_enumTypes[0].Descriptor()
}

func (ApplicationStatus) Type() protoreflect.EnumType {
	return &file_v1_proto_application_application_proto_enumTypes[0]
}

func (x ApplicationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationStatus.Descriptor instead.
func (ApplicationStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_application_application_proto_rawDescGZIP(), []int{0}
}

// ApplicationStage represents the current stage.
type ApplicationStage int32

const (
	// The application stage is unspecified.
	ApplicationStage_APPLICATION_STAGE_UNSPECIFIED ApplicationStage = 0
	// The application has been submitted.
	ApplicationStage_APPLICATION_STAGE_APPLICATION_SUBMITTED ApplicationStage = 1
	// The application is being screened.
	ApplicationStage_APPLICATION_STAGE_SCREENING ApplicationStage = 2
	// The candidate is in phone interview.
	ApplicationStage_APPLICATION_STAGE_PHONE_INTERVIEW ApplicationStage = 3
	// The candidate is in technical interview.
	ApplicationStage_APPLICATION_STAGE_TECHNICAL_INTERVIEW ApplicationStage = 4
	// The candidate is in on-site interview.
	ApplicationStage_APPLICATION_STAGE_ON_SITE_INTERVIEW ApplicationStage = 5
	// References are being checked.
	ApplicationStage_APPLICATION_STAGE_REFERENCE_CHECK ApplicationStage = 6
	// An offer has been made.
	ApplicationStage_APPLICATION_STAGE_OFFER ApplicationStage = 7
	// Salary negotiation is in progress.
	ApplicationStage_APPLICATION_STAGE_NEGOTIATION ApplicationStage = 8
	// The candidate has been hired.
	ApplicationStage_APPLICATION_STAGE_HIRED ApplicationStage = 9
)

// Enum value maps for ApplicationStage.
var (
	ApplicationStage_name = map[int32]string{
		0: "APPLICATION_STAGE_UNSPECIFIED",
		1: "APPLICATION_STAGE_APPLICATION_SUBMITTED",
		2: "APPLICATION_STAGE_SCREENING",
		3: "APPLICATION_STAGE_PHONE_INTERVIEW",
		4: "APPLICATION_STAGE_TECHNICAL_INTERVIEW",
		5: "APPLICATION_STAGE_ON_SITE_INTERVIEW",
		6: "APPLICATION_STAGE_REFERENCE_CHECK",
		7: "APPLICATION_STAGE_OFFER",
		8: "APPLICATION_STAGE_NEGOTIATION",
		9: "APPLICATION_STAGE_HIRED",
	}
	ApplicationStage_value = map[string]int32{
		"APPLICATION_STAGE_UNSPECIFIED":           0,
		"APPLICATION_STAGE_APPLICATION_SUBMITTED": 1,
		"APPLICATION_STAGE_SCREENING":             2,
		"APPLICATION_STAGE_PHONE_INTERVIEW":       3,
		"APPLICATION_STAGE_TECHNICAL_INTERVIEW":   4,
		"APPLICATION_STAGE_ON_SITE_INTERVIEW":     5,
		"APPLICATION_STAGE_REFERENCE_CHECK":       6,
		"APPLICATION_STAGE_OFFER":                 7,
		"APPLICATION_STAGE_NEGOTIATION":           8,
		"APPLICATION_STAGE_HIRED":                 9,
	}
)

func (x ApplicationStage) Enum() *ApplicationStage {
	p := new(ApplicationStage)
	*p = x
	return p
}

func (x ApplicationStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationStage) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_application_application_proto_enumTypes[1].Descriptor()
}

func (ApplicationStage) Type() protoreflect.EnumType {
	return &file_v1_proto_application_application_proto_enumTypes[1]
}

func (x ApplicationStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationStage.Descriptor instead.
func (ApplicationStage) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_application_application_proto_rawDescGZIP(), []int{1}
}

// Application represents a job application.
type Application struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the application.
	// Format: `applications/{application}`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The unique identifier of the application.
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// The resource name of the job being applied for.
	// Format: `jobs/{job}`
	Job string `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	// The resource name of the candidate applying.
	// Format: `users/{user}`
	Candidate string `protobuf:"bytes,4,opt,name=candidate,proto3" json:"candidate,omitempty"`
	// The resource name of the company offering the job.
	// Format: `companies/{company}`
	Company string `protobuf:"bytes,5,opt,name=company,proto3" json:"company,omitempty"`
	// The current status of the application.
	Status ApplicationStatus `protobuf:"varint,6,opt,name=status,proto3,enum=koloney.application.v1.ApplicationStatus" json:"status,omitempty"`
	// The current stage of the application.
	Stage ApplicationStage `protobuf:"varint,7,opt,name=stage,proto3,enum=koloney.application.v1.ApplicationStage" json:"stage,omitempty"`
	// The application documents.
	Documents *ApplicationDocuments `protobuf:"bytes,8,opt,name=documents,proto3" json:"documents,omitempty"`
	// The application notes.
	Notes *ApplicationNotes `protobuf:"bytes,9,opt,name=notes,proto3" json:"notes,omitempty"`
	// The application timeline.
	Timeline *ApplicationTimeline `protobuf:"bytes,10,opt,name=timeline,proto3" json:"timeline,omitempty"`
	// The creation timestamp of the application.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last update timestamp of the application.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_v1_proto_application_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_application_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_v1_proto_application_application_proto_rawDescGZIP(), []int{0}
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Application) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *Application) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *Application) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Application) GetStatus() ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED
}

func (x *Application) GetStage() ApplicationStage {
	if x != nil {
		return x.Stage
	}
	return ApplicationStage_APPLICATION_STAGE_UNSPECIFIED
}

func (x *Application) GetDocuments() *ApplicationDocuments {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *Application) GetNotes() *ApplicationNotes {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *Application) GetTimeline() *ApplicationTimeline {
	if x != nil {
		return x.Timeline
	}
	return nil
}

func (x *Application) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Application) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// ApplicationDocuments represents attached files.
type ApplicationDocuments struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the resume.
	// Format: `documents/{document}`
	Resume string `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"`
	// The resource name of the cover letter.
	// Format: `documents/{document}`
	CoverLetter string `protobuf:"bytes,2,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	// Additional document resource names.
	// Format: `documents/{document}`
	AdditionalDocuments []string `protobuf:"bytes,3,rep,name=additional_documents,json=additionalDocuments,proto3" json:"additional_documents,omitempty"`
	// Portfolio links.
	PortfolioLinks []string `protobuf:"bytes,4,rep,name=portfolio_links,json=portfolioLinks,proto3" json:"portfolio_links,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplicationDocuments) Reset() {
	*x = ApplicationDocuments{}
	mi := &file_v1_proto_application_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationDocuments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationDocuments) ProtoMessage() {}

func (x *ApplicationDocuments) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_application_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationDocuments.ProtoReflect.Descriptor instead.
func (*ApplicationDocuments) Descriptor() ([]byte, []int) {
	return file_v1_proto_application_application_proto_rawDescGZIP(), []int{1}
}

func (x *ApplicationDocuments) GetResume() string {
	if x != nil {
		return x.Resume
	}
	return ""
}

func (x *ApplicationDocuments) GetCoverLetter() string {
	if x != nil {
		return x.CoverLetter
	}
	return ""
}

func (x *ApplicationDocuments) GetAdditionalDocuments() []string {
	if x != nil {
		return x.AdditionalDocuments
	}
	return nil
}

func (x *ApplicationDocuments) GetPortfolioLinks() []string {
	if x != nil {
		return x.PortfolioLinks
	}
	return nil
}

// ApplicationNotes represents internal notes.
type ApplicationNotes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Notes from recruiters.
	RecruiterNotes []string `protobuf:"bytes,1,rep,name=recruiter_notes,json=recruiterNotes,proto3" json:"recruiter_notes,omitempty"`
	// Notes from hiring managers.
	HiringManagerNotes []string `protobuf:"bytes,2,rep,name=hiring_manager_notes,json=hiringManagerNotes,proto3" json:"hiring_manager_notes,omitempty"`
	// Notes from candidates.
	CandidateNotes []string `protobuf:"bytes,3,rep,name=candidate_notes,json=candidateNotes,proto3" json:"candidate_notes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplicationNotes) Reset() {
	*x = ApplicationNotes{}
	mi := &file_v1_proto_application_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationNotes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationNotes) ProtoMessage() {}

func (x *ApplicationNotes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_application_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationNotes.ProtoReflect.Descriptor instead.
func (*ApplicationNotes) Descriptor() ([]byte, []int) {
	return file_v1_proto_application_application_proto_rawDescGZIP(), []int{2}
}

func (x *ApplicationNotes) GetRecruiterNotes() []string {
	if x != nil {
		return x.RecruiterNotes
	}
	return nil
}

func (x *ApplicationNotes) GetHiringManagerNotes() []string {
	if x != nil {
		return x.HiringManagerNotes
	}
	return nil
}

func (x *ApplicationNotes) GetCandidateNotes() []string {
	if x != nil {
		return x.CandidateNotes
	}
	return nil
}

// ApplicationTimeline represents key dates.
type ApplicationTimeline struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When the application was submitted.
	SubmittedTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=submitted_time,json=submittedTime,proto3" json:"submitted_time,omitempty"`
	// When the application was first reviewed.
	FirstReviewTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=first_review_time,json=firstReviewTime,proto3" json:"first_review_time,omitempty"`
	// When the candidate was last contacted.
	LastContactTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_contact_time,json=lastContactTime,proto3" json:"last_contact_time,omitempty"`
	// The estimated decision date.
	EstimatedDecisionTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=estimated_decision_time,json=estimatedDecisionTime,proto3" json:"estimated_decision_time,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ApplicationTimeline) Reset() {
	*x = ApplicationTimeline{}
	mi := &file_v1_proto_application_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationTimeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationTimeline) ProtoMessage() {}

func (x *ApplicationTimeline) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_application_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationTimeline.ProtoReflect.Descriptor instead.
func (*ApplicationTimeline) Descriptor() ([]byte, []int) {
	return file_v1_proto_application_application_proto_rawDescGZIP(), []int{3}
}

func (x *ApplicationTimeline) GetSubmittedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedTime
	}
	return nil
}

func (x *ApplicationTimeline) GetFirstReviewTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstReviewTime
	}
	return nil
}

func (x *ApplicationTimeline) GetLastContactTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastContactTime
	}
	return nil
}

func (x *ApplicationTimeline) GetEstimatedDecisionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedDecisionTime
	}
	return nil
}

// CreateApplicationRequest contains the information needed to create a new application.
type CreateApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The application resource to create.
	Application   *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicationRequest) Reset() {
	*x = CreateApplicationRequest{}
	mi := &file_v1_proto_application_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationRequest) ProtoMessage() {}

func (x *CreateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_application_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_v1_proto_application_application_proto_rawDescGZIP(), []int{4}
}

func (x *CreateApplicationRequest) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

// GetApplicationRequest contains the name of the application to retrieve.
type GetApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the application to retrieve.
	// Format: `applications/{application}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationRequest) Reset() {
	*x = GetApplicationRequest{}
	mi := &file_v1_proto_application_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationRequest) ProtoMessage() {}

func (x *GetApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_application_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationRequest) Descriptor() ([]byte, []int) {
	return file_v1_proto_application_application_proto_rawDescGZIP(), []int{5}
}

func (x *GetApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// UpdateApplicationRequest contains the fields that can be updated for an application.
type UpdateApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The application resource which replaces the resource on the server.
	Application *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	// The list of fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationRequest) Reset() {
	*x = UpdateApplicationRequest{}
	mi := &file_v1_proto_application_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationRequest) ProtoMessage() {}

func (x *UpdateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_application_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_v1_proto_application_application_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateApplicationRequest) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *UpdateApplicationRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// DeleteApplicationRequest contains the name of the application to delete.
type DeleteApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the application to delete.
	// Format: `applications/{application}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationRequest) Reset() {
	*x = DeleteApplicationRequest{}
	mi := &file_v1_proto_application_application_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationRequest) ProtoMessage() {}

func (x *DeleteApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_application_application_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationRequest.ProtoReflect.Descriptor instead.
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) {
	return file_v1_proto_application_application_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListApplicationsRequest contains pagination and filtering parameters.
type ListApplicationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of applications to return.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token value returned from a previous List request, if any.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter applications by job.
	// Format: `jobs/{job}`
	Job *string `protobuf:"bytes,3,opt,name=job,proto3,oneof" json:"job,omitempty"`
	// Filter applications by candidate.
	// Format: `users/{user}`
	Candidate *string `protobuf:"bytes,4,opt,name=candidate,proto3,oneof" json:"candidate,omitempty"`
	// Filter applications by company.
	// Format: `companies/{company}`
	Company *string `protobuf:"bytes,5,opt,name=company,proto3,oneof" json:"company,omitempty"`
	// Filter applications by status.
	Status *ApplicationStatus `protobuf:"varint,6,opt,name=status,proto3,enum=koloney.application.v1.ApplicationStatus,oneof" json:"status,omitempty"`
	// Filter applications by stage.
	Stage         *ApplicationStage `protobuf:"varint,7,opt,name=stage,proto3,enum=koloney.application.v1.ApplicationStage,oneof" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_v1_proto_application_application_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_application_application_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_v1_proto_application_application_proto_rawDescGZIP(), []int{8}
}

func (x *ListApplicationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListApplicationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListApplicationsRequest) GetJob() string {
	if x != nil && x.Job != nil {
		return *x.Job
	}
	return ""
}

func (x *ListApplicationsRequest) GetCandidate() string {
	if x != nil && x.Candidate != nil {
		return *x.Candidate
	}
	return ""
}

func (x *ListApplicationsRequest) GetCompany() string {
	if x != nil && x.Company != nil {
		return *x.Company
	}
	return ""
}

func (x *ListApplicationsRequest) GetStatus() ApplicationStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED
}

func (x *ListApplicationsRequest) GetStage() ApplicationStage {
	if x != nil && x.Stage != nil {
		return *x.Stage
	}
	return ApplicationStage_APPLICATION_STAGE_UNSPECIFIED
}

// ListApplicationsResponse contains a page of applications and pagination info.
type ListApplicationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of applications.
	Applications []*Application `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	// Token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// The total number of applications matching the request.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_v1_proto_application_application_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_application_application_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_v1_proto_application_application_proto_rawDescGZIP(), []int{9}
}

func (x *ListApplicationsResponse) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *ListApplicationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListApplicationsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// UpdateApplicationStatusRequest contains the new status for an application.
type UpdateApplicationStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The application resource to update.
	Application   *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationStatusRequest) Reset() {
	*x = UpdateApplicationStatusRequest{}
	mi := &file_v1_proto_application_application_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationStatusRequest) ProtoMessage() {}

func (x *UpdateApplicationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_application_application_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_proto_application_application_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateApplicationStatusRequest) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

var File_v1_proto_application_application_proto protoreflect.FileDescriptor

const file_v1_proto_application_application_proto_rawDesc = "" +
	"\n" +
	"&v1/proto/application/application.proto\x12\x16koloney.application.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\"\xc6\x05\n" +
	"\vApplication\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12\x15\n" +
	"\x03uid\x18\x02 \x01(\tB\x03\xe0A\x03R\x03uid\x12\x15\n" +
	"\x03job\x18\x03 \x01(\tB\x03\xe0A\x02R\x03job\x12!\n" +
	"\tcandidate\x18\x04 \x01(\tB\x03\xe0A\x02R\tcandidate\x12\x1d\n" +
	"\acompany\x18\x05 \x01(\tB\x03\xe0A\x03R\acompany\x12F\n" +
	"\x06status\x18\x06 \x01(\x0e2).koloney.application.v1.ApplicationStatusB\x03\xe0A\x03R\x06status\x12C\n" +
	"\x05stage\x18\a \x01(\x0e2(.koloney.application.v1.ApplicationStageB\x03\xe0A\x03R\x05stage\x12J\n" +
	"\tdocuments\x18\b \x01(\v2,.koloney.application.v1.ApplicationDocumentsR\tdocuments\x12>\n" +
	"\x05notes\x18\t \x01(\v2(.koloney.application.v1.ApplicationNotesR\x05notes\x12L\n" +
	"\btimeline\x18\n" +
	" \x01(\v2+.koloney.application.v1.ApplicationTimelineB\x03\xe0A\x03R\btimeline\x12@\n" +
	"\vcreate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime:C\xeaA@\n" +
	"\"koloney.googleapis.com/Application\x12\x1aapplications/{application}\"\xad\x01\n" +
	"\x14ApplicationDocuments\x12\x16\n" +
	"\x06resume\x18\x01 \x01(\tR\x06resume\x12!\n" +
	"\fcover_letter\x18\x02 \x01(\tR\vcoverLetter\x121\n" +
	"\x14additional_documents\x18\x03 \x03(\tR\x13additionalDocuments\x12'\n" +
	"\x0fportfolio_links\x18\x04 \x03(\tR\x0eportfolioLinks\"\x96\x01\n" +
	"\x10ApplicationNotes\x12'\n" +
	"\x0frecruiter_notes\x18\x01 \x03(\tR\x0erecruiterNotes\x120\n" +
	"\x14hiring_manager_notes\x18\x02 \x03(\tR\x12hiringManagerNotes\x12'\n" +
	"\x0fcandidate_notes\x18\x03 \x03(\tR\x0ecandidateNotes\"\xbc\x02\n" +
	"\x13ApplicationTimeline\x12A\n" +
	"\x0esubmitted_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\rsubmittedTime\x12F\n" +
	"\x11first_review_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0ffirstReviewTime\x12F\n" +
	"\x11last_contact_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastContactTime\x12R\n" +
	"\x17estimated_decision_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x15estimatedDecisionTime\"f\n" +
	"\x18CreateApplicationRequest\x12J\n" +
	"\vapplication\x18\x01 \x01(\v2#.koloney.application.v1.ApplicationB\x03\xe0A\x02R\vapplication\"0\n" +
	"\x15GetApplicationRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"\xa3\x01\n" +
	"\x18UpdateApplicationRequest\x12J\n" +
	"\vapplication\x18\x01 \x01(\v2#.koloney.application.v1.ApplicationB\x03\xe0A\x02R\vapplication\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"3\n" +
	"\x18DeleteApplicationRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"\xf2\x02\n" +
	"\x17ListApplicationsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x15\n" +
	"\x03job\x18\x03 \x01(\tH\x00R\x03job\x88\x01\x01\x12!\n" +
	"\tcandidate\x18\x04 \x01(\tH\x01R\tcandidate\x88\x01\x01\x12\x1d\n" +
	"\acompany\x18\x05 \x01(\tH\x02R\acompany\x88\x01\x01\x12F\n" +
	"\x06status\x18\x06 \x01(\x0e2).koloney.application.v1.ApplicationStatusH\x03R\x06status\x88\x01\x01\x12C\n" +
	"\x05stage\x18\a \x01(\x0e2(.koloney.application.v1.ApplicationStageH\x04R\x05stage\x88\x01\x01B\x06\n" +
	"\x04_jobB\f\n" +
	"\n" +
	"_candidateB\n" +
	"\n" +
	"\b_companyB\t\n" +
	"\a_statusB\b\n" +
	"\x06_stage\"\xaa\x01\n" +
	"\x18ListApplicationsResponse\x12G\n" +
	"\fapplications\x18\x01 \x03(\v2#.koloney.application.v1.ApplicationR\fapplications\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"l\n" +
	"\x1eUpdateApplicationStatusRequest\x12J\n" +
	"\vapplication\x18\x01 \x01(\v2#.koloney.application.v1.ApplicationB\x03\xe0A\x02R\vapplication*\xcc\x02\n" +
	"\x11ApplicationStatus\x12\"\n" +
	"\x1eAPPLICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18APPLICATION_STATUS_DRAFT\x10\x01\x12 \n" +
	"\x1cAPPLICATION_STATUS_SUBMITTED\x10\x02\x12#\n" +
	"\x1fAPPLICATION_STATUS_UNDER_REVIEW\x10\x03\x12#\n" +
	"\x1fAPPLICATION_STATUS_INTERVIEWING\x10\x04\x12%\n" +
	"!APPLICATION_STATUS_OFFER_EXTENDED\x10\x05\x12\x1f\n" +
	"\x1bAPPLICATION_STATUS_ACCEPTED\x10\x06\x12\x1f\n" +
	"\x1bAPPLICATION_STATUS_REJECTED\x10\a\x12 \n" +
	"\x1cAPPLICATION_STATUS_WITHDRAWN\x10\b*\x82\x03\n" +
	"\x10ApplicationStage\x12!\n" +
	"\x1dAPPLICATION_STAGE_UNSPECIFIED\x10\x00\x12+\n" +
	"'APPLICATION_STAGE_APPLICATION_SUBMITTED\x10\x01\x12\x1f\n" +
	"\x1bAPPLICATION_STAGE_SCREENING\x10\x02\x12%\n" +
	"!APPLICATION_STAGE_PHONE_INTERVIEW\x10\x03\x12)\n" +
	"%APPLICATION_STAGE_TECHNICAL_INTERVIEW\x10\x04\x12'\n" +
	"#APPLICATION_STAGE_ON_SITE_INTERVIEW\x10\x05\x12%\n" +
	"!APPLICATION_STAGE_REFERENCE_CHECK\x10\x06\x12\x1b\n" +
	"\x17APPLICATION_STAGE_OFFER\x10\a\x12!\n" +
	"\x1dAPPLICATION_STAGE_NEGOTIATION\x10\b\x12\x1b\n" +
	"\x17APPLICATION_STAGE_HIRED\x10\t2\xa8\a\n" +
	"\x12ApplicationService\x12\x91\x01\n" +
	"\x11CreateApplication\x120.koloney.application.v1.CreateApplicationRequest\x1a#.koloney.application.v1.Application\"%\x82\xd3\xe4\x93\x02\x1f:\vapplication\"\x10/v1/applications\x12\x87\x01\n" +
	"\x0eGetApplication\x12-.koloney.application.v1.GetApplicationRequest\x1a#.koloney.application.v1.Application\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/{name=applications/*}\x12\xa6\x01\n" +
	"\x11UpdateApplication\x120.koloney.application.v1.UpdateApplicationRequest\x1a#.koloney.application.v1.Application\":\x82\xd3\xe4\x93\x024:\vapplication2%/v1/{application.name=applications/*}\x12\x80\x01\n" +
	"\x11DeleteApplication\x120.koloney.application.v1.DeleteApplicationRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/{name=applications/*}\x12\x8f\x01\n" +
	"\x10ListApplications\x12/.koloney.application.v1.ListApplicationsRequest\x1a0.koloney.application.v1.ListApplicationsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/applications\x12\xb5\x01\n" +
	"\x17UpdateApplicationStatus\x126.koloney.application.v1.UpdateApplicationStatusRequest\x1a#.koloney.application.v1.Application\"=\x82\xd3\xe4\x93\x027:\x01*22/v1/{application.name=applications/*}:updateStatusB\xe1\x01\n" +
	"\x1acom.koloney.application.v1B\x10ApplicationProtoP\x01Z7koloney-protos/v1/go/v1/proto/application;applicationv1\xa2\x02\x03KAX\xaa\x02\x16Koloney.Application.V1\xca\x02\x16Koloney\\Application\\V1\xe2\x02\"Koloney\\Application\\V1\\GPBMetadata\xea\x02\x18Koloney::Application::V1b\x06proto3"

var (
	file_v1_proto_application_application_proto_rawDescOnce sync.Once
	file_v1_proto_application_application_proto_rawDescData []byte
)

func file_v1_proto_application_application_proto_rawDescGZIP() []byte {
	file_v1_proto_application_application_proto_rawDescOnce.Do(func() {
		file_v1_proto_application_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_proto_application_application_proto_rawDesc), len(file_v1_proto_application_application_proto_rawDesc)))
	})
	return file_v1_proto_application_application_proto_rawDescData
}

var file_v1_proto_application_application_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_proto_application_application_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v1_proto_application_application_proto_goTypes = []any{
	(ApplicationStatus)(0),                 // 0: koloney.application.v1.ApplicationStatus
	(ApplicationStage)(0),                  // 1: koloney.application.v1.ApplicationStage
	(*Application)(nil),                    // 2: koloney.application.v1.Application
	(*ApplicationDocuments)(nil),           // 3: koloney.application.v1.ApplicationDocuments
	(*ApplicationNotes)(nil),               // 4: koloney.application.v1.ApplicationNotes
	(*ApplicationTimeline)(nil),            // 5: koloney.application.v1.ApplicationTimeline
	(*CreateApplicationRequest)(nil),       // 6: koloney.application.v1.CreateApplicationRequest
	(*GetApplicationRequest)(nil),          // 7: koloney.application.v1.GetApplicationRequest
	(*UpdateApplicationRequest)(nil),       // 8: koloney.application.v1.UpdateApplicationRequest
	(*DeleteApplicationRequest)(nil),       // 9: koloney.application.v1.DeleteApplicationRequest
	(*ListApplicationsRequest)(nil),        // 10: koloney.application.v1.ListApplicationsRequest
	(*ListApplicationsResponse)(nil),       // 11: koloney.application.v1.ListApplicationsResponse
	(*UpdateApplicationStatusRequest)(nil), // 12: koloney.application.v1.UpdateApplicationStatusRequest
	(*timestamppb.Timestamp)(nil),          // 13: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),          // 14: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                  // 15: google.protobuf.Empty
}
var file_v1_proto_application_application_proto_depIdxs = []int32{
	0,  // 0: koloney.application.v1.Application.status:type_name -> koloney.application.v1.ApplicationStatus
	1,  // 1: koloney.application.v1.Application.stage:type_name -> koloney.application.v1.ApplicationStage
	3,  // 2: koloney.application.v1.Application.documents:type_name -> koloney.application.v1.ApplicationDocuments
	4,  // 3: koloney.application.v1.Application.notes:type_name -> koloney.application.v1.ApplicationNotes
	5,  // 4: koloney.application.v1.Application.timeline:type_name -> koloney.application.v1.ApplicationTimeline
	13, // 5: koloney.application.v1.Application.create_time:type_name -> google.protobuf.Timestamp
	13, // 6: koloney.application.v1.Application.update_time:type_name -> google.protobuf.Timestamp
	13, // 7: koloney.application.v1.ApplicationTimeline.submitted_time:type_name -> google.protobuf.Timestamp
	13, // 8: koloney.application.v1.ApplicationTimeline.first_review_time:type_name -> google.protobuf.Timestamp
	13, // 9: koloney.application.v1.ApplicationTimeline.last_contact_time:type_name -> google.protobuf.Timestamp
	13, // 10: koloney.application.v1.ApplicationTimeline.estimated_decision_time:type_name -> google.protobuf.Timestamp
	2,  // 11: koloney.application.v1.CreateApplicationRequest.application:type_name -> koloney.application.v1.Application
	2,  // 12: koloney.application.v1.UpdateApplicationRequest.application:type_name -> koloney.application.v1.Application
	14, // 13: koloney.application.v1.UpdateApplicationRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 14: koloney.application.v1.ListApplicationsRequest.status:type_name -> koloney.application.v1.ApplicationStatus
	1,  // 15: koloney.application.v1.ListApplicationsRequest.stage:type_name -> koloney.application.v1.ApplicationStage
	2,  // 16: koloney.application.v1.ListApplicationsResponse.applications:type_name -> koloney.application.v1.Application
	2,  // 17: koloney.application.v1.UpdateApplicationStatusRequest.application:type_name -> koloney.application.v1.Application
	6,  // 18: koloney.application.v1.ApplicationService.CreateApplication:input_type -> koloney.application.v1.CreateApplicationRequest
	7,  // 19: koloney.application.v1.ApplicationService.GetApplication:input_type -> koloney.application.v1.GetApplicationRequest
	8,  // 20: koloney.application.v1.ApplicationService.UpdateApplication:input_type -> koloney.application.v1.UpdateApplicationRequest
	9,  // 21: koloney.application.v1.ApplicationService.DeleteApplication:input_type -> koloney.application.v1.DeleteApplicationRequest
	10, // 22: koloney.application.v1.ApplicationService.ListApplications:input_type -> koloney.application.v1.ListApplicationsRequest
	12, // 23: koloney.application.v1.ApplicationService.UpdateApplicationStatus:input_type -> koloney.application.v1.UpdateApplicationStatusRequest
	2,  // 24: koloney.application.v1.ApplicationService.CreateApplication:output_type -> koloney.application.v1.Application
	2,  // 25: koloney.application.v1.ApplicationService.GetApplication:output_type -> koloney.application.v1.Application
	2,  // 26: koloney.application.v1.ApplicationService.UpdateApplication:output_type -> koloney.application.v1.Application
	15, // 27: koloney.application.v1.ApplicationService.DeleteApplication:output_type -> google.protobuf.Empty
	11, // 28: koloney.application.v1.ApplicationService.ListApplications:output_type -> koloney.application.v1.ListApplicationsResponse
	2,  // 29: koloney.application.v1.ApplicationService.UpdateApplicationStatus:output_type -> koloney.application.v1.Application
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_v1_proto_application_application_proto_init() }
func file_v1_proto_application_application_proto_init() {
	if File_v1_proto_application_application_proto != nil {
		return
	}
	file_v1_proto_application_application_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_proto_application_application_proto_rawDesc), len(file_v1_proto_application_application_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_proto_application_application_proto_goTypes,
		DependencyIndexes: file_v1_proto_application_application_proto_depIdxs,
		EnumInfos:         file_v1_proto_application_application_proto_enumTypes,
		MessageInfos:      file_v1_proto_application_application_proto_msgTypes,
	}.Build()
	File_v1_proto_application_application_proto = out.File
	file_v1_proto_application_application_proto_goTypes = nil
	file_v1_proto_application_application_proto_depIdxs = nil
}
