// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: v1/job/entities.proto

package job

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "koloney-protos/go/v1/google/api"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobStatus represents the current state of a job.
type JobStatus int32

const (
	// The job status is unspecified.
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	// The job is in draft mode.
	JobStatus_JOB_STATUS_DRAFT JobStatus = 1
	// The job is active and accepting applications.
	JobStatus_JOB_STATUS_ACTIVE JobStatus = 2
	// The job is paused and not accepting applications.
	JobStatus_JOB_STATUS_PAUSED JobStatus = 3
	// The job is closed and no longer accepting applications.
	JobStatus_JOB_STATUS_CLOSED JobStatus = 4
	// The job has expired.
	JobStatus_JOB_STATUS_EXPIRED JobStatus = 5
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_DRAFT",
		2: "JOB_STATUS_ACTIVE",
		3: "JOB_STATUS_PAUSED",
		4: "JOB_STATUS_CLOSED",
		5: "JOB_STATUS_EXPIRED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_DRAFT":       1,
		"JOB_STATUS_ACTIVE":      2,
		"JOB_STATUS_PAUSED":      3,
		"JOB_STATUS_CLOSED":      4,
		"JOB_STATUS_EXPIRED":     5,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_job_entities_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_v1_job_entities_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_job_entities_proto_rawDescGZIP(), []int{0}
}

// JobType represents the employment type.
type JobType int32

const (
	// The job type is unspecified.
	JobType_JOB_TYPE_UNSPECIFIED JobType = 0
	// Full-time employment.
	JobType_JOB_TYPE_FULL_TIME JobType = 1
	// Part-time employment.
	JobType_JOB_TYPE_PART_TIME JobType = 2
	// Contract work.
	JobType_JOB_TYPE_CONTRACT JobType = 3
	// Internship position.
	JobType_JOB_TYPE_INTERNSHIP JobType = 4
	// Freelance work.
	JobType_JOB_TYPE_FREELANCE JobType = 5
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNSPECIFIED",
		1: "JOB_TYPE_FULL_TIME",
		2: "JOB_TYPE_PART_TIME",
		3: "JOB_TYPE_CONTRACT",
		4: "JOB_TYPE_INTERNSHIP",
		5: "JOB_TYPE_FREELANCE",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNSPECIFIED": 0,
		"JOB_TYPE_FULL_TIME":   1,
		"JOB_TYPE_PART_TIME":   2,
		"JOB_TYPE_CONTRACT":    3,
		"JOB_TYPE_INTERNSHIP":  4,
		"JOB_TYPE_FREELANCE":   5,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_job_entities_proto_enumTypes[1].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_v1_job_entities_proto_enumTypes[1]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_v1_job_entities_proto_rawDescGZIP(), []int{1}
}

// Job represents a job posting.
type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the job.
	// Format: `jobs/{job}`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The unique identifier of the job.
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// The job title.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// The job description.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// The resource name of the company that posted the job.
	// Format: `companies/{company}`
	Company string `protobuf:"bytes,5,opt,name=company,proto3" json:"company,omitempty"`
	// The resource name of the recruiter who posted the job.
	// Format: `users/{user}`
	Recruiter string `protobuf:"bytes,6,opt,name=recruiter,proto3" json:"recruiter,omitempty"`
	// The current status of the job.
	Status JobStatus `protobuf:"varint,7,opt,name=status,proto3,enum=koloney.v1.job.JobStatus" json:"status,omitempty"`
	// The type of employment.
	Type JobType `protobuf:"varint,8,opt,name=type,proto3,enum=koloney.v1.job.JobType" json:"type,omitempty"`
	// The job location information.
	Location *JobLocation `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	// The job requirements.
	Requirements *JobRequirements `protobuf:"bytes,10,opt,name=requirements,proto3" json:"requirements,omitempty"`
	// The job benefits.
	Benefits *JobBenefits `protobuf:"bytes,11,opt,name=benefits,proto3" json:"benefits,omitempty"`
	// The creation timestamp of the job.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last update timestamp of the job.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// The expiration timestamp of the job.
	ExpireTime    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_v1_job_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_v1_job_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_v1_job_entities_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Job) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Job) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Job) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Job) GetRecruiter() string {
	if x != nil {
		return x.Recruiter
	}
	return ""
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *Job) GetType() JobType {
	if x != nil {
		return x.Type
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *Job) GetLocation() *JobLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Job) GetRequirements() *JobRequirements {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *Job) GetBenefits() *JobBenefits {
	if x != nil {
		return x.Benefits
	}
	return nil
}

func (x *Job) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Job) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Job) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

// JobLocation represents where the job is located.
type JobLocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The city where the job is located.
	City string `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	// The state or province where the job is located.
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// The country where the job is located.
	Country string `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	// Whether remote work is allowed.
	RemoteAllowed bool `protobuf:"varint,4,opt,name=remote_allowed,json=remoteAllowed,proto3" json:"remote_allowed,omitempty"`
	// The full address of the job location.
	Address       string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobLocation) Reset() {
	*x = JobLocation{}
	mi := &file_v1_job_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobLocation) ProtoMessage() {}

func (x *JobLocation) ProtoReflect() protoreflect.Message {
	mi := &file_v1_job_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobLocation.ProtoReflect.Descriptor instead.
func (*JobLocation) Descriptor() ([]byte, []int) {
	return file_v1_job_entities_proto_rawDescGZIP(), []int{1}
}

func (x *JobLocation) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *JobLocation) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *JobLocation) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *JobLocation) GetRemoteAllowed() bool {
	if x != nil {
		return x.RemoteAllowed
	}
	return false
}

func (x *JobLocation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// JobRequirements represents the skills and experience needed.
type JobRequirements struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The required skills for the job.
	Skills []string `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	// The minimum years of experience required.
	MinExperienceYears int32 `protobuf:"varint,2,opt,name=min_experience_years,json=minExperienceYears,proto3" json:"min_experience_years,omitempty"`
	// The required education level.
	EducationLevel string `protobuf:"bytes,3,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	// The required certifications.
	Certifications []string `protobuf:"bytes,4,rep,name=certifications,proto3" json:"certifications,omitempty"`
	// Additional requirements description.
	Description   string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequirements) Reset() {
	*x = JobRequirements{}
	mi := &file_v1_job_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequirements) ProtoMessage() {}

func (x *JobRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_v1_job_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequirements.ProtoReflect.Descriptor instead.
func (*JobRequirements) Descriptor() ([]byte, []int) {
	return file_v1_job_entities_proto_rawDescGZIP(), []int{2}
}

func (x *JobRequirements) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *JobRequirements) GetMinExperienceYears() int32 {
	if x != nil {
		return x.MinExperienceYears
	}
	return 0
}

func (x *JobRequirements) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *JobRequirements) GetCertifications() []string {
	if x != nil {
		return x.Certifications
	}
	return nil
}

func (x *JobRequirements) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// JobBenefits represents what the company offers.
type JobBenefits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of benefits offered.
	Benefits []string `protobuf:"bytes,1,rep,name=benefits,proto3" json:"benefits,omitempty"`
	// The salary range for the position.
	SalaryRange string `protobuf:"bytes,2,opt,name=salary_range,json=salaryRange,proto3" json:"salary_range,omitempty"`
	// Whether health insurance is provided.
	HealthInsurance bool `protobuf:"varint,3,opt,name=health_insurance,json=healthInsurance,proto3" json:"health_insurance,omitempty"`
	// Whether a retirement plan is provided.
	RetirementPlan bool `protobuf:"varint,4,opt,name=retirement_plan,json=retirementPlan,proto3" json:"retirement_plan,omitempty"`
	// Whether paid time off is provided.
	PaidTimeOff   bool `protobuf:"varint,5,opt,name=paid_time_off,json=paidTimeOff,proto3" json:"paid_time_off,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobBenefits) Reset() {
	*x = JobBenefits{}
	mi := &file_v1_job_entities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobBenefits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobBenefits) ProtoMessage() {}

func (x *JobBenefits) ProtoReflect() protoreflect.Message {
	mi := &file_v1_job_entities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobBenefits.ProtoReflect.Descriptor instead.
func (*JobBenefits) Descriptor() ([]byte, []int) {
	return file_v1_job_entities_proto_rawDescGZIP(), []int{3}
}

func (x *JobBenefits) GetBenefits() []string {
	if x != nil {
		return x.Benefits
	}
	return nil
}

func (x *JobBenefits) GetSalaryRange() string {
	if x != nil {
		return x.SalaryRange
	}
	return ""
}

func (x *JobBenefits) GetHealthInsurance() bool {
	if x != nil {
		return x.HealthInsurance
	}
	return false
}

func (x *JobBenefits) GetRetirementPlan() bool {
	if x != nil {
		return x.RetirementPlan
	}
	return false
}

func (x *JobBenefits) GetPaidTimeOff() bool {
	if x != nil {
		return x.PaidTimeOff
	}
	return false
}

var File_v1_job_entities_proto protoreflect.FileDescriptor

const file_v1_job_entities_proto_rawDesc = "" +
	"\n" +
	"\x15v1/job/entities.proto\x12\x0ekoloney.v1.job\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x05\n" +
	"\x03Job\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12\x15\n" +
	"\x03uid\x18\x02 \x01(\tB\x03\xe0A\x03R\x03uid\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tB\x03\xe0A\x02R\x05title\x12%\n" +
	"\vdescription\x18\x04 \x01(\tB\x03\xe0A\x02R\vdescription\x12\x1d\n" +
	"\acompany\x18\x05 \x01(\tB\x03\xe0A\x02R\acompany\x12!\n" +
	"\trecruiter\x18\x06 \x01(\tB\x03\xe0A\x02R\trecruiter\x126\n" +
	"\x06status\x18\a \x01(\x0e2\x19.koloney.v1.job.JobStatusB\x03\xe0A\x03R\x06status\x120\n" +
	"\x04type\x18\b \x01(\x0e2\x17.koloney.v1.job.JobTypeB\x03\xe0A\x02R\x04type\x12<\n" +
	"\blocation\x18\t \x01(\v2\x1b.koloney.v1.job.JobLocationB\x03\xe0A\x02R\blocation\x12C\n" +
	"\frequirements\x18\n" +
	" \x01(\v2\x1f.koloney.v1.job.JobRequirementsR\frequirements\x127\n" +
	"\bbenefits\x18\v \x01(\v2\x1b.koloney.v1.job.JobBenefitsR\bbenefits\x12@\n" +
	"\vcreate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12;\n" +
	"\vexpire_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireTime:+\xeaA(\n" +
	"\x1akoloney.googleapis.com/Job\x12\n" +
	"jobs/{job}\"\x9c\x01\n" +
	"\vJobLocation\x12\x17\n" +
	"\x04city\x18\x01 \x01(\tB\x03\xe0A\x02R\x04city\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1d\n" +
	"\acountry\x18\x03 \x01(\tB\x03\xe0A\x02R\acountry\x12%\n" +
	"\x0eremote_allowed\x18\x04 \x01(\bR\rremoteAllowed\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\"\xce\x01\n" +
	"\x0fJobRequirements\x12\x16\n" +
	"\x06skills\x18\x01 \x03(\tR\x06skills\x120\n" +
	"\x14min_experience_years\x18\x02 \x01(\x05R\x12minExperienceYears\x12'\n" +
	"\x0feducation_level\x18\x03 \x01(\tR\x0eeducationLevel\x12&\n" +
	"\x0ecertifications\x18\x04 \x03(\tR\x0ecertifications\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xc4\x01\n" +
	"\vJobBenefits\x12\x1a\n" +
	"\bbenefits\x18\x01 \x03(\tR\bbenefits\x12!\n" +
	"\fsalary_range\x18\x02 \x01(\tR\vsalaryRange\x12)\n" +
	"\x10health_insurance\x18\x03 \x01(\bR\x0fhealthInsurance\x12'\n" +
	"\x0fretirement_plan\x18\x04 \x01(\bR\x0eretirementPlan\x12\"\n" +
	"\rpaid_time_off\x18\x05 \x01(\bR\vpaidTimeOff*\x9a\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10JOB_STATUS_DRAFT\x10\x01\x12\x15\n" +
	"\x11JOB_STATUS_ACTIVE\x10\x02\x12\x15\n" +
	"\x11JOB_STATUS_PAUSED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_CLOSED\x10\x04\x12\x16\n" +
	"\x12JOB_STATUS_EXPIRED\x10\x05*\x9b\x01\n" +
	"\aJobType\x12\x18\n" +
	"\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_TYPE_FULL_TIME\x10\x01\x12\x16\n" +
	"\x12JOB_TYPE_PART_TIME\x10\x02\x12\x15\n" +
	"\x11JOB_TYPE_CONTRACT\x10\x03\x12\x17\n" +
	"\x13JOB_TYPE_INTERNSHIP\x10\x04\x12\x16\n" +
	"\x12JOB_TYPE_FREELANCE\x10\x05B\x9a\x01\n" +
	"\x12com.koloney.v1.jobB\rEntitiesProtoP\x01Z\x1bkoloney-protos/go/v1/v1/job\xa2\x02\x03KVJ\xaa\x02\x0eKoloney.V1.Job\xca\x02\x0eKoloney\\V1\\Job\xe2\x02\x1aKoloney\\V1\\Job\\GPBMetadata\xea\x02\x10Koloney::V1::Jobb\x06proto3"

var (
	file_v1_job_entities_proto_rawDescOnce sync.Once
	file_v1_job_entities_proto_rawDescData []byte
)

func file_v1_job_entities_proto_rawDescGZIP() []byte {
	file_v1_job_entities_proto_rawDescOnce.Do(func() {
		file_v1_job_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_job_entities_proto_rawDesc), len(file_v1_job_entities_proto_rawDesc)))
	})
	return file_v1_job_entities_proto_rawDescData
}

var file_v1_job_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_job_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_job_entities_proto_goTypes = []any{
	(JobStatus)(0),                // 0: koloney.v1.job.JobStatus
	(JobType)(0),                  // 1: koloney.v1.job.JobType
	(*Job)(nil),                   // 2: koloney.v1.job.Job
	(*JobLocation)(nil),           // 3: koloney.v1.job.JobLocation
	(*JobRequirements)(nil),       // 4: koloney.v1.job.JobRequirements
	(*JobBenefits)(nil),           // 5: koloney.v1.job.JobBenefits
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_v1_job_entities_proto_depIdxs = []int32{
	0, // 0: koloney.v1.job.Job.status:type_name -> koloney.v1.job.JobStatus
	1, // 1: koloney.v1.job.Job.type:type_name -> koloney.v1.job.JobType
	3, // 2: koloney.v1.job.Job.location:type_name -> koloney.v1.job.JobLocation
	4, // 3: koloney.v1.job.Job.requirements:type_name -> koloney.v1.job.JobRequirements
	5, // 4: koloney.v1.job.Job.benefits:type_name -> koloney.v1.job.JobBenefits
	6, // 5: koloney.v1.job.Job.create_time:type_name -> google.protobuf.Timestamp
	6, // 6: koloney.v1.job.Job.update_time:type_name -> google.protobuf.Timestamp
	6, // 7: koloney.v1.job.Job.expire_time:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_v1_job_entities_proto_init() }
func file_v1_job_entities_proto_init() {
	if File_v1_job_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_job_entities_proto_rawDesc), len(file_v1_job_entities_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_job_entities_proto_goTypes,
		DependencyIndexes: file_v1_job_entities_proto_depIdxs,
		EnumInfos:         file_v1_job_entities_proto_enumTypes,
		MessageInfos:      file_v1_job_entities_proto_msgTypes,
	}.Build()
	File_v1_job_entities_proto = out.File
	file_v1_job_entities_proto_goTypes = nil
	file_v1_job_entities_proto_depIdxs = nil
}
