// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file v1/proto/koloney/koloney.proto (package koloney, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetBalanceRequest, GetBalanceResponse } from "./koloney_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * KoloneyService provides financial operations
 *
 * @generated from service koloney.KoloneyService
 */
export const KoloneyService = {
  typeName: "koloney.KoloneyService",
  methods: {
    /**
     * GetBalance retrieves the current balance
     *
     * @generated from rpc koloney.KoloneyService.GetBalance
     */
    getBalance: {
      name: "GetBalance",
      I: GetBalanceRequest,
      O: GetBalanceResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

