// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: koloney/job/v1/service.proto

package jobv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "koloney-protos/go/v1/google/api"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateJobRequest contains the information needed to create a new job.
type CreateJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The job resource to create.
	Job           *Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_koloney_job_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_job_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_koloney_job_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJobRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

// GetJobRequest contains the name of the job to retrieve.
type GetJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the job to retrieve.
	// Format: `jobs/{job}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_koloney_job_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_job_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_koloney_job_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// UpdateJobRequest contains the fields that can be updated for a job.
type UpdateJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The job resource which replaces the resource on the server.
	Job *Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	// The list of fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobRequest) Reset() {
	*x = UpdateJobRequest{}
	mi := &file_koloney_job_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobRequest) ProtoMessage() {}

func (x *UpdateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_job_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobRequest) Descriptor() ([]byte, []int) {
	return file_koloney_job_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateJobRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *UpdateJobRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// DeleteJobRequest contains the name of the job to delete.
type DeleteJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the job to delete.
	// Format: `jobs/{job}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobRequest) Reset() {
	*x = DeleteJobRequest{}
	mi := &file_koloney_job_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobRequest) ProtoMessage() {}

func (x *DeleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_job_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobRequest.ProtoReflect.Descriptor instead.
func (*DeleteJobRequest) Descriptor() ([]byte, []int) {
	return file_koloney_job_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListJobsRequest contains pagination and filtering parameters.
type ListJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of jobs to return.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token value returned from a previous List request, if any.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter jobs by company.
	// Format: `companies/{company}`
	Company *string `protobuf:"bytes,3,opt,name=company,proto3,oneof" json:"company,omitempty"`
	// Filter jobs by recruiter.
	// Format: `users/{user}`
	Recruiter *string `protobuf:"bytes,4,opt,name=recruiter,proto3,oneof" json:"recruiter,omitempty"`
	// Filter jobs by status.
	Status *JobStatus `protobuf:"varint,5,opt,name=status,proto3,enum=koloney.job.v1.JobStatus,oneof" json:"status,omitempty"`
	// Filter jobs by type.
	Type          *JobType `protobuf:"varint,6,opt,name=type,proto3,enum=koloney.job.v1.JobType,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_koloney_job_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_job_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_koloney_job_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListJobsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListJobsRequest) GetCompany() string {
	if x != nil && x.Company != nil {
		return *x.Company
	}
	return ""
}

func (x *ListJobsRequest) GetRecruiter() string {
	if x != nil && x.Recruiter != nil {
		return *x.Recruiter
	}
	return ""
}

func (x *ListJobsRequest) GetStatus() JobStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *ListJobsRequest) GetType() JobType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

// ListJobsResponse contains a page of jobs and pagination info.
type ListJobsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of jobs.
	Jobs []*Job `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	// Token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// The total number of jobs matching the request.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_koloney_job_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_job_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_koloney_job_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListJobsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// SearchJobsRequest contains search criteria.
type SearchJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The search query.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// The maximum number of jobs to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token value returned from a previous Search request, if any.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter jobs by location.
	Location *string `protobuf:"bytes,4,opt,name=location,proto3,oneof" json:"location,omitempty"`
	// Filter jobs by type.
	Type *JobType `protobuf:"varint,5,opt,name=type,proto3,enum=koloney.job.v1.JobType,oneof" json:"type,omitempty"`
	// Filter jobs by minimum experience.
	MinExperience *int32 `protobuf:"varint,6,opt,name=min_experience,json=minExperience,proto3,oneof" json:"min_experience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchJobsRequest) Reset() {
	*x = SearchJobsRequest{}
	mi := &file_koloney_job_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchJobsRequest) ProtoMessage() {}

func (x *SearchJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_job_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchJobsRequest.ProtoReflect.Descriptor instead.
func (*SearchJobsRequest) Descriptor() ([]byte, []int) {
	return file_koloney_job_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *SearchJobsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchJobsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *SearchJobsRequest) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *SearchJobsRequest) GetType() JobType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *SearchJobsRequest) GetMinExperience() int32 {
	if x != nil && x.MinExperience != nil {
		return *x.MinExperience
	}
	return 0
}

// SearchJobsResponse contains search results.
type SearchJobsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of jobs matching the search criteria.
	Jobs []*Job `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	// Token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// The total number of jobs matching the search criteria.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchJobsResponse) Reset() {
	*x = SearchJobsResponse{}
	mi := &file_koloney_job_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchJobsResponse) ProtoMessage() {}

func (x *SearchJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_job_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchJobsResponse.ProtoReflect.Descriptor instead.
func (*SearchJobsResponse) Descriptor() ([]byte, []int) {
	return file_koloney_job_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *SearchJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *SearchJobsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *SearchJobsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// UpdateJobStatusRequest contains the new status for a job.
type UpdateJobStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The job resource to update.
	Job           *Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobStatusRequest) Reset() {
	*x = UpdateJobStatusRequest{}
	mi := &file_koloney_job_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobStatusRequest) ProtoMessage() {}

func (x *UpdateJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_job_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_koloney_job_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateJobStatusRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

// CreateJobResponse contains the created job.
type CreateJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created job.
	Job           *Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobResponse) Reset() {
	*x = CreateJobResponse{}
	mi := &file_koloney_job_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobResponse) ProtoMessage() {}

func (x *CreateJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_job_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobResponse.ProtoReflect.Descriptor instead.
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return file_koloney_job_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

// GetJobResponse contains the retrieved job.
type GetJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The retrieved job.
	Job           *Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_koloney_job_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_job_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_koloney_job_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

// UpdateJobResponse contains the updated job.
type UpdateJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated job.
	Job           *Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobResponse) Reset() {
	*x = UpdateJobResponse{}
	mi := &file_koloney_job_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobResponse) ProtoMessage() {}

func (x *UpdateJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_job_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobResponse.ProtoReflect.Descriptor instead.
func (*UpdateJobResponse) Descriptor() ([]byte, []int) {
	return file_koloney_job_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

// DeleteJobResponse indicates successful deletion.
type DeleteJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobResponse) Reset() {
	*x = DeleteJobResponse{}
	mi := &file_koloney_job_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobResponse) ProtoMessage() {}

func (x *DeleteJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_job_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobResponse.ProtoReflect.Descriptor instead.
func (*DeleteJobResponse) Descriptor() ([]byte, []int) {
	return file_koloney_job_v1_service_proto_rawDescGZIP(), []int{12}
}

// UpdateJobStatusResponse contains the updated job.
type UpdateJobStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated job.
	Job           *Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobStatusResponse) Reset() {
	*x = UpdateJobStatusResponse{}
	mi := &file_koloney_job_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobStatusResponse) ProtoMessage() {}

func (x *UpdateJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_job_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_koloney_job_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateJobStatusResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_koloney_job_v1_service_proto protoreflect.FileDescriptor

const file_koloney_job_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1ckoloney/job/v1/service.proto\x12\x0ekoloney.job.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a google/protobuf/field_mask.proto\x1a\x1dkoloney/job/v1/entities.proto\">\n" +
	"\x10CreateJobRequest\x12*\n" +
	"\x03job\x18\x01 \x01(\v2\x13.koloney.job.v1.JobB\x03\xe0A\x02R\x03job\"(\n" +
	"\rGetJobRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"{\n" +
	"\x10UpdateJobRequest\x12*\n" +
	"\x03job\x18\x01 \x01(\v2\x13.koloney.job.v1.JobB\x03\xe0A\x02R\x03job\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"+\n" +
	"\x10DeleteJobRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"\xa7\x02\n" +
	"\x0fListJobsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1d\n" +
	"\acompany\x18\x03 \x01(\tH\x00R\acompany\x88\x01\x01\x12!\n" +
	"\trecruiter\x18\x04 \x01(\tH\x01R\trecruiter\x88\x01\x01\x126\n" +
	"\x06status\x18\x05 \x01(\x0e2\x19.koloney.job.v1.JobStatusH\x02R\x06status\x88\x01\x01\x120\n" +
	"\x04type\x18\x06 \x01(\x0e2\x17.koloney.job.v1.JobTypeH\x03R\x04type\x88\x01\x01B\n" +
	"\n" +
	"\b_companyB\f\n" +
	"\n" +
	"_recruiterB\t\n" +
	"\a_statusB\a\n" +
	"\x05_type\"\x82\x01\n" +
	"\x10ListJobsResponse\x12'\n" +
	"\x04jobs\x18\x01 \x03(\v2\x13.koloney.job.v1.JobR\x04jobs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"\x92\x02\n" +
	"\x11SearchJobsRequest\x12\x19\n" +
	"\x05query\x18\x01 \x01(\tB\x03\xe0A\x02R\x05query\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x1f\n" +
	"\blocation\x18\x04 \x01(\tH\x00R\blocation\x88\x01\x01\x120\n" +
	"\x04type\x18\x05 \x01(\x0e2\x17.koloney.job.v1.JobTypeH\x01R\x04type\x88\x01\x01\x12*\n" +
	"\x0emin_experience\x18\x06 \x01(\x05H\x02R\rminExperience\x88\x01\x01B\v\n" +
	"\t_locationB\a\n" +
	"\x05_typeB\x11\n" +
	"\x0f_min_experience\"\x84\x01\n" +
	"\x12SearchJobsResponse\x12'\n" +
	"\x04jobs\x18\x01 \x03(\v2\x13.koloney.job.v1.JobR\x04jobs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"D\n" +
	"\x16UpdateJobStatusRequest\x12*\n" +
	"\x03job\x18\x01 \x01(\v2\x13.koloney.job.v1.JobB\x03\xe0A\x02R\x03job\":\n" +
	"\x11CreateJobResponse\x12%\n" +
	"\x03job\x18\x01 \x01(\v2\x13.koloney.job.v1.JobR\x03job\"7\n" +
	"\x0eGetJobResponse\x12%\n" +
	"\x03job\x18\x01 \x01(\v2\x13.koloney.job.v1.JobR\x03job\":\n" +
	"\x11UpdateJobResponse\x12%\n" +
	"\x03job\x18\x01 \x01(\v2\x13.koloney.job.v1.JobR\x03job\"\x13\n" +
	"\x11DeleteJobResponse\"@\n" +
	"\x17UpdateJobStatusResponse\x12%\n" +
	"\x03job\x18\x01 \x01(\v2\x13.koloney.job.v1.JobR\x03job2\x9f\x06\n" +
	"\n" +
	"JobService\x12g\n" +
	"\tCreateJob\x12 .koloney.job.v1.CreateJobRequest\x1a!.koloney.job.v1.CreateJobResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x03job\"\b/v1/jobs\x12b\n" +
	"\x06GetJob\x12\x1d.koloney.job.v1.GetJobRequest\x1a\x1e.koloney.job.v1.GetJobResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/{name=jobs/*}\x12t\n" +
	"\tUpdateJob\x12 .koloney.job.v1.UpdateJobRequest\x1a!.koloney.job.v1.UpdateJobResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x03job2\x15/v1/{job.name=jobs/*}\x12k\n" +
	"\tDeleteJob\x12 .koloney.job.v1.DeleteJobRequest\x1a!.koloney.job.v1.DeleteJobResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/{name=jobs/*}\x12_\n" +
	"\bListJobs\x12\x1f.koloney.job.v1.ListJobsRequest\x1a .koloney.job.v1.ListJobsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/jobs\x12l\n" +
	"\n" +
	"SearchJobs\x12!.koloney.job.v1.SearchJobsRequest\x1a\".koloney.job.v1.SearchJobsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/jobs:search\x12\x91\x01\n" +
	"\x0fUpdateJobStatus\x12&.koloney.job.v1.UpdateJobStatusRequest\x1a'.koloney.job.v1.UpdateJobStatusResponse\"-\x82\xd3\xe4\x93\x02':\x01*2\"/v1/{job.name=jobs/*}:updateStatusB\xa7\x01\n" +
	"\x12com.koloney.job.v1B\fServiceProtoP\x01Z)koloney-protos/go/v1/koloney/job/v1;jobv1\xa2\x02\x03KJX\xaa\x02\x0eKoloney.Job.V1\xca\x02\x0eKoloney\\Job\\V1\xe2\x02\x1aKoloney\\Job\\V1\\GPBMetadata\xea\x02\x10Koloney::Job::V1b\x06proto3"

var (
	file_koloney_job_v1_service_proto_rawDescOnce sync.Once
	file_koloney_job_v1_service_proto_rawDescData []byte
)

func file_koloney_job_v1_service_proto_rawDescGZIP() []byte {
	file_koloney_job_v1_service_proto_rawDescOnce.Do(func() {
		file_koloney_job_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_koloney_job_v1_service_proto_rawDesc), len(file_koloney_job_v1_service_proto_rawDesc)))
	})
	return file_koloney_job_v1_service_proto_rawDescData
}

var file_koloney_job_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_koloney_job_v1_service_proto_goTypes = []any{
	(*CreateJobRequest)(nil),        // 0: koloney.job.v1.CreateJobRequest
	(*GetJobRequest)(nil),           // 1: koloney.job.v1.GetJobRequest
	(*UpdateJobRequest)(nil),        // 2: koloney.job.v1.UpdateJobRequest
	(*DeleteJobRequest)(nil),        // 3: koloney.job.v1.DeleteJobRequest
	(*ListJobsRequest)(nil),         // 4: koloney.job.v1.ListJobsRequest
	(*ListJobsResponse)(nil),        // 5: koloney.job.v1.ListJobsResponse
	(*SearchJobsRequest)(nil),       // 6: koloney.job.v1.SearchJobsRequest
	(*SearchJobsResponse)(nil),      // 7: koloney.job.v1.SearchJobsResponse
	(*UpdateJobStatusRequest)(nil),  // 8: koloney.job.v1.UpdateJobStatusRequest
	(*CreateJobResponse)(nil),       // 9: koloney.job.v1.CreateJobResponse
	(*GetJobResponse)(nil),          // 10: koloney.job.v1.GetJobResponse
	(*UpdateJobResponse)(nil),       // 11: koloney.job.v1.UpdateJobResponse
	(*DeleteJobResponse)(nil),       // 12: koloney.job.v1.DeleteJobResponse
	(*UpdateJobStatusResponse)(nil), // 13: koloney.job.v1.UpdateJobStatusResponse
	(*Job)(nil),                     // 14: koloney.job.v1.Job
	(*fieldmaskpb.FieldMask)(nil),   // 15: google.protobuf.FieldMask
	(JobStatus)(0),                  // 16: koloney.job.v1.JobStatus
	(JobType)(0),                    // 17: koloney.job.v1.JobType
}
var file_koloney_job_v1_service_proto_depIdxs = []int32{
	14, // 0: koloney.job.v1.CreateJobRequest.job:type_name -> koloney.job.v1.Job
	14, // 1: koloney.job.v1.UpdateJobRequest.job:type_name -> koloney.job.v1.Job
	15, // 2: koloney.job.v1.UpdateJobRequest.update_mask:type_name -> google.protobuf.FieldMask
	16, // 3: koloney.job.v1.ListJobsRequest.status:type_name -> koloney.job.v1.JobStatus
	17, // 4: koloney.job.v1.ListJobsRequest.type:type_name -> koloney.job.v1.JobType
	14, // 5: koloney.job.v1.ListJobsResponse.jobs:type_name -> koloney.job.v1.Job
	17, // 6: koloney.job.v1.SearchJobsRequest.type:type_name -> koloney.job.v1.JobType
	14, // 7: koloney.job.v1.SearchJobsResponse.jobs:type_name -> koloney.job.v1.Job
	14, // 8: koloney.job.v1.UpdateJobStatusRequest.job:type_name -> koloney.job.v1.Job
	14, // 9: koloney.job.v1.CreateJobResponse.job:type_name -> koloney.job.v1.Job
	14, // 10: koloney.job.v1.GetJobResponse.job:type_name -> koloney.job.v1.Job
	14, // 11: koloney.job.v1.UpdateJobResponse.job:type_name -> koloney.job.v1.Job
	14, // 12: koloney.job.v1.UpdateJobStatusResponse.job:type_name -> koloney.job.v1.Job
	0,  // 13: koloney.job.v1.JobService.CreateJob:input_type -> koloney.job.v1.CreateJobRequest
	1,  // 14: koloney.job.v1.JobService.GetJob:input_type -> koloney.job.v1.GetJobRequest
	2,  // 15: koloney.job.v1.JobService.UpdateJob:input_type -> koloney.job.v1.UpdateJobRequest
	3,  // 16: koloney.job.v1.JobService.DeleteJob:input_type -> koloney.job.v1.DeleteJobRequest
	4,  // 17: koloney.job.v1.JobService.ListJobs:input_type -> koloney.job.v1.ListJobsRequest
	6,  // 18: koloney.job.v1.JobService.SearchJobs:input_type -> koloney.job.v1.SearchJobsRequest
	8,  // 19: koloney.job.v1.JobService.UpdateJobStatus:input_type -> koloney.job.v1.UpdateJobStatusRequest
	9,  // 20: koloney.job.v1.JobService.CreateJob:output_type -> koloney.job.v1.CreateJobResponse
	10, // 21: koloney.job.v1.JobService.GetJob:output_type -> koloney.job.v1.GetJobResponse
	11, // 22: koloney.job.v1.JobService.UpdateJob:output_type -> koloney.job.v1.UpdateJobResponse
	12, // 23: koloney.job.v1.JobService.DeleteJob:output_type -> koloney.job.v1.DeleteJobResponse
	5,  // 24: koloney.job.v1.JobService.ListJobs:output_type -> koloney.job.v1.ListJobsResponse
	7,  // 25: koloney.job.v1.JobService.SearchJobs:output_type -> koloney.job.v1.SearchJobsResponse
	13, // 26: koloney.job.v1.JobService.UpdateJobStatus:output_type -> koloney.job.v1.UpdateJobStatusResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_koloney_job_v1_service_proto_init() }
func file_koloney_job_v1_service_proto_init() {
	if File_koloney_job_v1_service_proto != nil {
		return
	}
	file_koloney_job_v1_entities_proto_init()
	file_koloney_job_v1_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_koloney_job_v1_service_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_koloney_job_v1_service_proto_rawDesc), len(file_koloney_job_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_koloney_job_v1_service_proto_goTypes,
		DependencyIndexes: file_koloney_job_v1_service_proto_depIdxs,
		MessageInfos:      file_koloney_job_v1_service_proto_msgTypes,
	}.Build()
	File_koloney_job_v1_service_proto = out.File
	file_koloney_job_v1_service_proto_goTypes = nil
	file_koloney_job_v1_service_proto_depIdxs = nil
}
