// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/proto/payment/entities.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentType represents the type of payment
type PaymentType int32

const (
	PaymentType_PAYMENT_TYPE_UNSPECIFIED      PaymentType = 0
	PaymentType_PAYMENT_TYPE_SUBSCRIPTION     PaymentType = 1
	PaymentType_PAYMENT_TYPE_JOB_POSTING      PaymentType = 2
	PaymentType_PAYMENT_TYPE_PREMIUM_FEATURES PaymentType = 3
	PaymentType_PAYMENT_TYPE_REFUND           PaymentType = 4
)

// Enum value maps for PaymentType.
var (
	PaymentType_name = map[int32]string{
		0: "PAYMENT_TYPE_UNSPECIFIED",
		1: "PAYMENT_TYPE_SUBSCRIPTION",
		2: "PAYMENT_TYPE_JOB_POSTING",
		3: "PAYMENT_TYPE_PREMIUM_FEATURES",
		4: "PAYMENT_TYPE_REFUND",
	}
	PaymentType_value = map[string]int32{
		"PAYMENT_TYPE_UNSPECIFIED":      0,
		"PAYMENT_TYPE_SUBSCRIPTION":     1,
		"PAYMENT_TYPE_JOB_POSTING":      2,
		"PAYMENT_TYPE_PREMIUM_FEATURES": 3,
		"PAYMENT_TYPE_REFUND":           4,
	}
)

func (x PaymentType) Enum() *PaymentType {
	p := new(PaymentType)
	*p = x
	return p
}

func (x PaymentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_payment_entities_proto_enumTypes[0].Descriptor()
}

func (PaymentType) Type() protoreflect.EnumType {
	return &file_v1_proto_payment_entities_proto_enumTypes[0]
}

func (x PaymentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentType.Descriptor instead.
func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_payment_entities_proto_rawDescGZIP(), []int{0}
}

// PaymentStatus represents the current status
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PROCESSING  PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_COMPLETED   PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_CANCELLED   PaymentStatus = 5
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 6
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_PROCESSING",
		3: "PAYMENT_STATUS_COMPLETED",
		4: "PAYMENT_STATUS_FAILED",
		5: "PAYMENT_STATUS_CANCELLED",
		6: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_PROCESSING":  2,
		"PAYMENT_STATUS_COMPLETED":   3,
		"PAYMENT_STATUS_FAILED":      4,
		"PAYMENT_STATUS_CANCELLED":   5,
		"PAYMENT_STATUS_REFUNDED":    6,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_payment_entities_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_v1_proto_payment_entities_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_payment_entities_proto_rawDescGZIP(), []int{1}
}

// PaymentMethod represents how payment is made
type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED   PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD   PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_DEBIT_CARD    PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_BANK_TRANSFER PaymentMethod = 3
	PaymentMethod_PAYMENT_METHOD_PAYPAL        PaymentMethod = 4
	PaymentMethod_PAYMENT_METHOD_STRIPE        PaymentMethod = 5
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CREDIT_CARD",
		2: "PAYMENT_METHOD_DEBIT_CARD",
		3: "PAYMENT_METHOD_BANK_TRANSFER",
		4: "PAYMENT_METHOD_PAYPAL",
		5: "PAYMENT_METHOD_STRIPE",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED":   0,
		"PAYMENT_METHOD_CREDIT_CARD":   1,
		"PAYMENT_METHOD_DEBIT_CARD":    2,
		"PAYMENT_METHOD_BANK_TRANSFER": 3,
		"PAYMENT_METHOD_PAYPAL":        4,
		"PAYMENT_METHOD_STRIPE":        5,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_payment_entities_proto_enumTypes[2].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_v1_proto_payment_entities_proto_enumTypes[2]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_payment_entities_proto_rawDescGZIP(), []int{2}
}

// Payment represents a financial transaction
type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Type          PaymentType            `protobuf:"varint,4,opt,name=type,proto3,enum=payment.PaymentType" json:"type,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,6,opt,name=method,proto3,enum=payment.PaymentMethod" json:"method,omitempty"`
	Amount        *PaymentAmount         `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Metadata      *PaymentMetadata       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_v1_proto_payment_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_payment_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_v1_proto_payment_entities_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Payment) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *Payment) GetType() PaymentType {
	if x != nil {
		return x.Type
	}
	return PaymentType_PAYMENT_TYPE_UNSPECIFIED
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *Payment) GetAmount() *PaymentAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Payment) GetMetadata() *PaymentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *Payment) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// PaymentAmount represents the monetary amount
type PaymentAmount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Amount         float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	TaxAmount      float64                `protobuf:"fixed64,3,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
	DiscountAmount float64                `protobuf:"fixed64,4,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	TotalAmount    float64                `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentAmount) Reset() {
	*x = PaymentAmount{}
	mi := &file_v1_proto_payment_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAmount) ProtoMessage() {}

func (x *PaymentAmount) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_payment_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAmount.ProtoReflect.Descriptor instead.
func (*PaymentAmount) Descriptor() ([]byte, []int) {
	return file_v1_proto_payment_entities_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentAmount) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentAmount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentAmount) GetTaxAmount() float64 {
	if x != nil {
		return x.TaxAmount
	}
	return 0
}

func (x *PaymentAmount) GetDiscountAmount() float64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *PaymentAmount) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

// PaymentMetadata represents additional information
type PaymentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	InvoiceId     string                 `protobuf:"bytes,2,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMetadata) Reset() {
	*x = PaymentMetadata{}
	mi := &file_v1_proto_payment_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMetadata) ProtoMessage() {}

func (x *PaymentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_payment_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMetadata.ProtoReflect.Descriptor instead.
func (*PaymentMetadata) Descriptor() ([]byte, []int) {
	return file_v1_proto_payment_entities_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PaymentMetadata) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *PaymentMetadata) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_v1_proto_payment_entities_proto protoreflect.FileDescriptor

const file_v1_proto_payment_entities_proto_rawDesc = "" +
	"\n" +
	"\x1fv1/proto/payment/entities.proto\x12\apayment\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x03\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.payment.PaymentTypeR\x04type\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12.\n" +
	"\x06method\x18\x06 \x01(\x0e2\x16.payment.PaymentMethodR\x06method\x12.\n" +
	"\x06amount\x18\a \x01(\v2\x16.payment.PaymentAmountR\x06amount\x124\n" +
	"\bmetadata\x18\b \x01(\v2\x18.payment.PaymentMetadataR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fprocessed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x12=\n" +
	"\fcompleted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xae\x01\n" +
	"\rPaymentAmount\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"tax_amount\x18\x03 \x01(\x01R\ttaxAmount\x12'\n" +
	"\x0fdiscount_amount\x18\x04 \x01(\x01R\x0ediscountAmount\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\"\x8d\x01\n" +
	"\x0fPaymentMetadata\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x02 \x01(\tR\tinvoiceId\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags*\xa4\x01\n" +
	"\vPaymentType\x12\x1c\n" +
	"\x18PAYMENT_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PAYMENT_TYPE_SUBSCRIPTION\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_TYPE_JOB_POSTING\x10\x02\x12!\n" +
	"\x1dPAYMENT_TYPE_PREMIUM_FEATURES\x10\x03\x12\x17\n" +
	"\x13PAYMENT_TYPE_REFUND\x10\x04*\xde\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_STATUS_PROCESSING\x10\x02\x12\x1c\n" +
	"\x18PAYMENT_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x04\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CANCELLED\x10\x05\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x06*\xc6\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_METHOD_DEBIT_CARD\x10\x02\x12 \n" +
	"\x1cPAYMENT_METHOD_BANK_TRANSFER\x10\x03\x12\x19\n" +
	"\x15PAYMENT_METHOD_PAYPAL\x10\x04\x12\x19\n" +
	"\x15PAYMENT_METHOD_STRIPE\x10\x05B\x7f\n" +
	"\vcom.paymentB\rEntitiesProtoP\x01Z%koloney-protos/v1/go/v1/proto/payment\xa2\x02\x03PXX\xaa\x02\aPayment\xca\x02\aPayment\xe2\x02\x13Payment\\GPBMetadata\xea\x02\aPaymentb\x06proto3"

var (
	file_v1_proto_payment_entities_proto_rawDescOnce sync.Once
	file_v1_proto_payment_entities_proto_rawDescData []byte
)

func file_v1_proto_payment_entities_proto_rawDescGZIP() []byte {
	file_v1_proto_payment_entities_proto_rawDescOnce.Do(func() {
		file_v1_proto_payment_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_proto_payment_entities_proto_rawDesc), len(file_v1_proto_payment_entities_proto_rawDesc)))
	})
	return file_v1_proto_payment_entities_proto_rawDescData
}

var file_v1_proto_payment_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_v1_proto_payment_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_proto_payment_entities_proto_goTypes = []any{
	(PaymentType)(0),              // 0: payment.PaymentType
	(PaymentStatus)(0),            // 1: payment.PaymentStatus
	(PaymentMethod)(0),            // 2: payment.PaymentMethod
	(*Payment)(nil),               // 3: payment.Payment
	(*PaymentAmount)(nil),         // 4: payment.PaymentAmount
	(*PaymentMetadata)(nil),       // 5: payment.PaymentMetadata
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_v1_proto_payment_entities_proto_depIdxs = []int32{
	0, // 0: payment.Payment.type:type_name -> payment.PaymentType
	1, // 1: payment.Payment.status:type_name -> payment.PaymentStatus
	2, // 2: payment.Payment.method:type_name -> payment.PaymentMethod
	4, // 3: payment.Payment.amount:type_name -> payment.PaymentAmount
	5, // 4: payment.Payment.metadata:type_name -> payment.PaymentMetadata
	6, // 5: payment.Payment.created_at:type_name -> google.protobuf.Timestamp
	6, // 6: payment.Payment.processed_at:type_name -> google.protobuf.Timestamp
	6, // 7: payment.Payment.completed_at:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_v1_proto_payment_entities_proto_init() }
func file_v1_proto_payment_entities_proto_init() {
	if File_v1_proto_payment_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_proto_payment_entities_proto_rawDesc), len(file_v1_proto_payment_entities_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_proto_payment_entities_proto_goTypes,
		DependencyIndexes: file_v1_proto_payment_entities_proto_depIdxs,
		EnumInfos:         file_v1_proto_payment_entities_proto_enumTypes,
		MessageInfos:      file_v1_proto_payment_entities_proto_msgTypes,
	}.Build()
	File_v1_proto_payment_entities_proto = out.File
	file_v1_proto_payment_entities_proto_goTypes = nil
	file_v1_proto_payment_entities_proto_depIdxs = nil
}
