// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: koloney/application/v1/service.proto

package applicationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "koloney-protos/go/v1/google/api"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateApplicationRequest contains the information needed to create a new application.
type CreateApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The application resource to create.
	Application   *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicationRequest) Reset() {
	*x = CreateApplicationRequest{}
	mi := &file_koloney_application_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationRequest) ProtoMessage() {}

func (x *CreateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_application_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_koloney_application_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateApplicationRequest) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

// GetApplicationRequest contains the name of the application to retrieve.
type GetApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the application to retrieve.
	// Format: `applications/{application}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationRequest) Reset() {
	*x = GetApplicationRequest{}
	mi := &file_koloney_application_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationRequest) ProtoMessage() {}

func (x *GetApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_application_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationRequest) Descriptor() ([]byte, []int) {
	return file_koloney_application_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// UpdateApplicationRequest contains the fields that can be updated for an application.
type UpdateApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The application resource which replaces the resource on the server.
	Application *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	// The list of fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationRequest) Reset() {
	*x = UpdateApplicationRequest{}
	mi := &file_koloney_application_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationRequest) ProtoMessage() {}

func (x *UpdateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_application_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_koloney_application_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateApplicationRequest) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *UpdateApplicationRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// DeleteApplicationRequest contains the name of the application to delete.
type DeleteApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the application to delete.
	// Format: `applications/{application}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationRequest) Reset() {
	*x = DeleteApplicationRequest{}
	mi := &file_koloney_application_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationRequest) ProtoMessage() {}

func (x *DeleteApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_application_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationRequest.ProtoReflect.Descriptor instead.
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) {
	return file_koloney_application_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListApplicationsRequest contains pagination and filtering parameters.
type ListApplicationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of applications to return.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token value returned from a previous List request, if any.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter applications by job.
	// Format: `jobs/{job}`
	Job *string `protobuf:"bytes,3,opt,name=job,proto3,oneof" json:"job,omitempty"`
	// Filter applications by candidate.
	// Format: `users/{user}`
	Candidate *string `protobuf:"bytes,4,opt,name=candidate,proto3,oneof" json:"candidate,omitempty"`
	// Filter applications by company.
	// Format: `companies/{company}`
	Company *string `protobuf:"bytes,5,opt,name=company,proto3,oneof" json:"company,omitempty"`
	// Filter applications by status.
	Status *ApplicationStatus `protobuf:"varint,6,opt,name=status,proto3,enum=koloney.application.v1.ApplicationStatus,oneof" json:"status,omitempty"`
	// Filter applications by stage.
	Stage         *ApplicationStage `protobuf:"varint,7,opt,name=stage,proto3,enum=koloney.application.v1.ApplicationStage,oneof" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_koloney_application_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_application_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_koloney_application_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListApplicationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListApplicationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListApplicationsRequest) GetJob() string {
	if x != nil && x.Job != nil {
		return *x.Job
	}
	return ""
}

func (x *ListApplicationsRequest) GetCandidate() string {
	if x != nil && x.Candidate != nil {
		return *x.Candidate
	}
	return ""
}

func (x *ListApplicationsRequest) GetCompany() string {
	if x != nil && x.Company != nil {
		return *x.Company
	}
	return ""
}

func (x *ListApplicationsRequest) GetStatus() ApplicationStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED
}

func (x *ListApplicationsRequest) GetStage() ApplicationStage {
	if x != nil && x.Stage != nil {
		return *x.Stage
	}
	return ApplicationStage_APPLICATION_STAGE_UNSPECIFIED
}

// ListApplicationsResponse contains a page of applications and pagination info.
type ListApplicationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of applications.
	Applications []*Application `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	// Token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// The total number of applications matching the request.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_koloney_application_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_application_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_koloney_application_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListApplicationsResponse) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *ListApplicationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListApplicationsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// UpdateApplicationStatusRequest contains the new status for an application.
type UpdateApplicationStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The application resource to update.
	Application   *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationStatusRequest) Reset() {
	*x = UpdateApplicationStatusRequest{}
	mi := &file_koloney_application_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationStatusRequest) ProtoMessage() {}

func (x *UpdateApplicationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_application_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return file_koloney_application_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateApplicationStatusRequest) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

// CreateApplicationResponse contains the created application.
type CreateApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created application.
	Application   *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicationResponse) Reset() {
	*x = CreateApplicationResponse{}
	mi := &file_koloney_application_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationResponse) ProtoMessage() {}

func (x *CreateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_application_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationResponse.ProtoReflect.Descriptor instead.
func (*CreateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_koloney_application_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateApplicationResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

// GetApplicationResponse contains the retrieved application.
type GetApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The retrieved application.
	Application   *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationResponse) Reset() {
	*x = GetApplicationResponse{}
	mi := &file_koloney_application_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationResponse) ProtoMessage() {}

func (x *GetApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_application_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationResponse) Descriptor() ([]byte, []int) {
	return file_koloney_application_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetApplicationResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

// UpdateApplicationResponse contains the updated application.
type UpdateApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated application.
	Application   *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationResponse) Reset() {
	*x = UpdateApplicationResponse{}
	mi := &file_koloney_application_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationResponse) ProtoMessage() {}

func (x *UpdateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_application_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationResponse.ProtoReflect.Descriptor instead.
func (*UpdateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_koloney_application_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateApplicationResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

// DeleteApplicationResponse indicates successful deletion.
type DeleteApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationResponse) Reset() {
	*x = DeleteApplicationResponse{}
	mi := &file_koloney_application_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationResponse) ProtoMessage() {}

func (x *DeleteApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_application_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationResponse.ProtoReflect.Descriptor instead.
func (*DeleteApplicationResponse) Descriptor() ([]byte, []int) {
	return file_koloney_application_v1_service_proto_rawDescGZIP(), []int{10}
}

// UpdateApplicationStatusResponse contains the updated application.
type UpdateApplicationStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated application.
	Application   *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationStatusResponse) Reset() {
	*x = UpdateApplicationStatusResponse{}
	mi := &file_koloney_application_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationStatusResponse) ProtoMessage() {}

func (x *UpdateApplicationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_application_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateApplicationStatusResponse) Descriptor() ([]byte, []int) {
	return file_koloney_application_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateApplicationStatusResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

var File_koloney_application_v1_service_proto protoreflect.FileDescriptor

const file_koloney_application_v1_service_proto_rawDesc = "" +
	"\n" +
	"$koloney/application/v1/service.proto\x12\x16koloney.application.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a google/protobuf/field_mask.proto\x1a%koloney/application/v1/entities.proto\"f\n" +
	"\x18CreateApplicationRequest\x12J\n" +
	"\vapplication\x18\x01 \x01(\v2#.koloney.application.v1.ApplicationB\x03\xe0A\x02R\vapplication\"0\n" +
	"\x15GetApplicationRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"\xa3\x01\n" +
	"\x18UpdateApplicationRequest\x12J\n" +
	"\vapplication\x18\x01 \x01(\v2#.koloney.application.v1.ApplicationB\x03\xe0A\x02R\vapplication\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"3\n" +
	"\x18DeleteApplicationRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"\xf2\x02\n" +
	"\x17ListApplicationsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x15\n" +
	"\x03job\x18\x03 \x01(\tH\x00R\x03job\x88\x01\x01\x12!\n" +
	"\tcandidate\x18\x04 \x01(\tH\x01R\tcandidate\x88\x01\x01\x12\x1d\n" +
	"\acompany\x18\x05 \x01(\tH\x02R\acompany\x88\x01\x01\x12F\n" +
	"\x06status\x18\x06 \x01(\x0e2).koloney.application.v1.ApplicationStatusH\x03R\x06status\x88\x01\x01\x12C\n" +
	"\x05stage\x18\a \x01(\x0e2(.koloney.application.v1.ApplicationStageH\x04R\x05stage\x88\x01\x01B\x06\n" +
	"\x04_jobB\f\n" +
	"\n" +
	"_candidateB\n" +
	"\n" +
	"\b_companyB\t\n" +
	"\a_statusB\b\n" +
	"\x06_stage\"\xaa\x01\n" +
	"\x18ListApplicationsResponse\x12G\n" +
	"\fapplications\x18\x01 \x03(\v2#.koloney.application.v1.ApplicationR\fapplications\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"l\n" +
	"\x1eUpdateApplicationStatusRequest\x12J\n" +
	"\vapplication\x18\x01 \x01(\v2#.koloney.application.v1.ApplicationB\x03\xe0A\x02R\vapplication\"b\n" +
	"\x19CreateApplicationResponse\x12E\n" +
	"\vapplication\x18\x01 \x01(\v2#.koloney.application.v1.ApplicationR\vapplication\"_\n" +
	"\x16GetApplicationResponse\x12E\n" +
	"\vapplication\x18\x01 \x01(\v2#.koloney.application.v1.ApplicationR\vapplication\"b\n" +
	"\x19UpdateApplicationResponse\x12E\n" +
	"\vapplication\x18\x01 \x01(\v2#.koloney.application.v1.ApplicationR\vapplication\"\x1b\n" +
	"\x19DeleteApplicationResponse\"h\n" +
	"\x1fUpdateApplicationStatusResponse\x12E\n" +
	"\vapplication\x18\x01 \x01(\v2#.koloney.application.v1.ApplicationR\vapplication2\xfe\a\n" +
	"\x12ApplicationService\x12\x9f\x01\n" +
	"\x11CreateApplication\x120.koloney.application.v1.CreateApplicationRequest\x1a1.koloney.application.v1.CreateApplicationResponse\"%\x82\xd3\xe4\x93\x02\x1f:\vapplication\"\x10/v1/applications\x12\x92\x01\n" +
	"\x0eGetApplication\x12-.koloney.application.v1.GetApplicationRequest\x1a..koloney.application.v1.GetApplicationResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/{name=applications/*}\x12\xb4\x01\n" +
	"\x11UpdateApplication\x120.koloney.application.v1.UpdateApplicationRequest\x1a1.koloney.application.v1.UpdateApplicationResponse\":\x82\xd3\xe4\x93\x024:\vapplication2%/v1/{application.name=applications/*}\x12\x9b\x01\n" +
	"\x11DeleteApplication\x120.koloney.application.v1.DeleteApplicationRequest\x1a1.koloney.application.v1.DeleteApplicationResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/{name=applications/*}\x12\x8f\x01\n" +
	"\x10ListApplications\x12/.koloney.application.v1.ListApplicationsRequest\x1a0.koloney.application.v1.ListApplicationsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/applications\x12\xc9\x01\n" +
	"\x17UpdateApplicationStatus\x126.koloney.application.v1.UpdateApplicationStatusRequest\x1a7.koloney.application.v1.UpdateApplicationStatusResponse\"=\x82\xd3\xe4\x93\x027:\x01*22/v1/{application.name=applications/*}:updateStatusB\xdf\x01\n" +
	"\x1acom.koloney.application.v1B\fServiceProtoP\x01Z9koloney-protos/go/v1/koloney/application/v1;applicationv1\xa2\x02\x03KAX\xaa\x02\x16Koloney.Application.V1\xca\x02\x16Koloney\\Application\\V1\xe2\x02\"Koloney\\Application\\V1\\GPBMetadata\xea\x02\x18Koloney::Application::V1b\x06proto3"

var (
	file_koloney_application_v1_service_proto_rawDescOnce sync.Once
	file_koloney_application_v1_service_proto_rawDescData []byte
)

func file_koloney_application_v1_service_proto_rawDescGZIP() []byte {
	file_koloney_application_v1_service_proto_rawDescOnce.Do(func() {
		file_koloney_application_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_koloney_application_v1_service_proto_rawDesc), len(file_koloney_application_v1_service_proto_rawDesc)))
	})
	return file_koloney_application_v1_service_proto_rawDescData
}

var file_koloney_application_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_koloney_application_v1_service_proto_goTypes = []any{
	(*CreateApplicationRequest)(nil),        // 0: koloney.application.v1.CreateApplicationRequest
	(*GetApplicationRequest)(nil),           // 1: koloney.application.v1.GetApplicationRequest
	(*UpdateApplicationRequest)(nil),        // 2: koloney.application.v1.UpdateApplicationRequest
	(*DeleteApplicationRequest)(nil),        // 3: koloney.application.v1.DeleteApplicationRequest
	(*ListApplicationsRequest)(nil),         // 4: koloney.application.v1.ListApplicationsRequest
	(*ListApplicationsResponse)(nil),        // 5: koloney.application.v1.ListApplicationsResponse
	(*UpdateApplicationStatusRequest)(nil),  // 6: koloney.application.v1.UpdateApplicationStatusRequest
	(*CreateApplicationResponse)(nil),       // 7: koloney.application.v1.CreateApplicationResponse
	(*GetApplicationResponse)(nil),          // 8: koloney.application.v1.GetApplicationResponse
	(*UpdateApplicationResponse)(nil),       // 9: koloney.application.v1.UpdateApplicationResponse
	(*DeleteApplicationResponse)(nil),       // 10: koloney.application.v1.DeleteApplicationResponse
	(*UpdateApplicationStatusResponse)(nil), // 11: koloney.application.v1.UpdateApplicationStatusResponse
	(*Application)(nil),                     // 12: koloney.application.v1.Application
	(*fieldmaskpb.FieldMask)(nil),           // 13: google.protobuf.FieldMask
	(ApplicationStatus)(0),                  // 14: koloney.application.v1.ApplicationStatus
	(ApplicationStage)(0),                   // 15: koloney.application.v1.ApplicationStage
}
var file_koloney_application_v1_service_proto_depIdxs = []int32{
	12, // 0: koloney.application.v1.CreateApplicationRequest.application:type_name -> koloney.application.v1.Application
	12, // 1: koloney.application.v1.UpdateApplicationRequest.application:type_name -> koloney.application.v1.Application
	13, // 2: koloney.application.v1.UpdateApplicationRequest.update_mask:type_name -> google.protobuf.FieldMask
	14, // 3: koloney.application.v1.ListApplicationsRequest.status:type_name -> koloney.application.v1.ApplicationStatus
	15, // 4: koloney.application.v1.ListApplicationsRequest.stage:type_name -> koloney.application.v1.ApplicationStage
	12, // 5: koloney.application.v1.ListApplicationsResponse.applications:type_name -> koloney.application.v1.Application
	12, // 6: koloney.application.v1.UpdateApplicationStatusRequest.application:type_name -> koloney.application.v1.Application
	12, // 7: koloney.application.v1.CreateApplicationResponse.application:type_name -> koloney.application.v1.Application
	12, // 8: koloney.application.v1.GetApplicationResponse.application:type_name -> koloney.application.v1.Application
	12, // 9: koloney.application.v1.UpdateApplicationResponse.application:type_name -> koloney.application.v1.Application
	12, // 10: koloney.application.v1.UpdateApplicationStatusResponse.application:type_name -> koloney.application.v1.Application
	0,  // 11: koloney.application.v1.ApplicationService.CreateApplication:input_type -> koloney.application.v1.CreateApplicationRequest
	1,  // 12: koloney.application.v1.ApplicationService.GetApplication:input_type -> koloney.application.v1.GetApplicationRequest
	2,  // 13: koloney.application.v1.ApplicationService.UpdateApplication:input_type -> koloney.application.v1.UpdateApplicationRequest
	3,  // 14: koloney.application.v1.ApplicationService.DeleteApplication:input_type -> koloney.application.v1.DeleteApplicationRequest
	4,  // 15: koloney.application.v1.ApplicationService.ListApplications:input_type -> koloney.application.v1.ListApplicationsRequest
	6,  // 16: koloney.application.v1.ApplicationService.UpdateApplicationStatus:input_type -> koloney.application.v1.UpdateApplicationStatusRequest
	7,  // 17: koloney.application.v1.ApplicationService.CreateApplication:output_type -> koloney.application.v1.CreateApplicationResponse
	8,  // 18: koloney.application.v1.ApplicationService.GetApplication:output_type -> koloney.application.v1.GetApplicationResponse
	9,  // 19: koloney.application.v1.ApplicationService.UpdateApplication:output_type -> koloney.application.v1.UpdateApplicationResponse
	10, // 20: koloney.application.v1.ApplicationService.DeleteApplication:output_type -> koloney.application.v1.DeleteApplicationResponse
	5,  // 21: koloney.application.v1.ApplicationService.ListApplications:output_type -> koloney.application.v1.ListApplicationsResponse
	11, // 22: koloney.application.v1.ApplicationService.UpdateApplicationStatus:output_type -> koloney.application.v1.UpdateApplicationStatusResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_koloney_application_v1_service_proto_init() }
func file_koloney_application_v1_service_proto_init() {
	if File_koloney_application_v1_service_proto != nil {
		return
	}
	file_koloney_application_v1_entities_proto_init()
	file_koloney_application_v1_service_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_koloney_application_v1_service_proto_rawDesc), len(file_koloney_application_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_koloney_application_v1_service_proto_goTypes,
		DependencyIndexes: file_koloney_application_v1_service_proto_depIdxs,
		MessageInfos:      file_koloney_application_v1_service_proto_msgTypes,
	}.Build()
	File_koloney_application_v1_service_proto = out.File
	file_koloney_application_v1_service_proto_goTypes = nil
	file_koloney_application_v1_service_proto_depIdxs = nil
}
