// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file koloney/koloney/v1/service.proto (package koloney.koloney.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file koloney/koloney/v1/service.proto.
 */
export const file_koloney_koloney_v1_service: GenFile = /*@__PURE__*/
  fileDesc("CiBrb2xvbmV5L2tvbG9uZXkvdjEvc2VydmljZS5wcm90bxISa29sb25leS5rb2xvbmV5LnYxIicKEUdldEJhbGFuY2VSZXF1ZXN0EhIKCmFjY291bnRfaWQYASABKAkiaQoSR2V0QmFsYW5jZVJlc3BvbnNlEg8KB2JhbGFuY2UYASABKAESEAoIY3VycmVuY3kYAiABKAkSMAoMbGFzdF91cGRhdGVkGAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcDKCAQoOS29sb25leVNlcnZpY2UScAoKR2V0QmFsYW5jZRIlLmtvbG9uZXkua29sb25leS52MS5HZXRCYWxhbmNlUmVxdWVzdBomLmtvbG9uZXkua29sb25leS52MS5HZXRCYWxhbmNlUmVzcG9uc2UiE4LT5JMCDRILL3YxL2JhbGFuY2VCwwEKFmNvbS5rb2xvbmV5LmtvbG9uZXkudjFCDFNlcnZpY2VQcm90b1ABWjFrb2xvbmV5LXByb3Rvcy9nby92MS9rb2xvbmV5L2tvbG9uZXkvdjE7a29sb25leXYxogIDS0tYqgISS29sb25leS5Lb2xvbmV5LlYxygISS29sb25leVxLb2xvbmV5XFYx4gIeS29sb25leVxLb2xvbmV5XFYxXEdQQk1ldGFkYXRh6gIUS29sb25leTo6S29sb25leTo6VjFiBnByb3RvMw", [file_google_api_annotations, file_google_protobuf_timestamp]);

/**
 * GetBalanceRequest is the request for getting balance
 *
 * @generated from message koloney.koloney.v1.GetBalanceRequest
 */
export type GetBalanceRequest = Message<"koloney.koloney.v1.GetBalanceRequest"> & {
  /**
   * @generated from field: string account_id = 1;
   */
  accountId: string;
};

/**
 * Describes the message koloney.koloney.v1.GetBalanceRequest.
 * Use `create(GetBalanceRequestSchema)` to create a new message.
 */
export const GetBalanceRequestSchema: GenMessage<GetBalanceRequest> = /*@__PURE__*/
  messageDesc(file_koloney_koloney_v1_service, 0);

/**
 * GetBalanceResponse is the response containing balance information
 *
 * @generated from message koloney.koloney.v1.GetBalanceResponse
 */
export type GetBalanceResponse = Message<"koloney.koloney.v1.GetBalanceResponse"> & {
  /**
   * @generated from field: double balance = 1;
   */
  balance: number;

  /**
   * @generated from field: string currency = 2;
   */
  currency: string;

  /**
   * @generated from field: google.protobuf.Timestamp last_updated = 3;
   */
  lastUpdated?: Timestamp;
};

/**
 * Describes the message koloney.koloney.v1.GetBalanceResponse.
 * Use `create(GetBalanceResponseSchema)` to create a new message.
 */
export const GetBalanceResponseSchema: GenMessage<GetBalanceResponse> = /*@__PURE__*/
  messageDesc(file_koloney_koloney_v1_service, 1);

/**
 * KoloneyService provides financial operations
 *
 * @generated from service koloney.koloney.v1.KoloneyService
 */
export const KoloneyService: GenService<{
  /**
   * GetBalance retrieves the current balance
   *
   * @generated from rpc koloney.koloney.v1.KoloneyService.GetBalance
   */
  getBalance: {
    methodKind: "unary";
    input: typeof GetBalanceRequestSchema;
    output: typeof GetBalanceResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_koloney_koloney_v1_service, 0);

