# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from koloney.koloney.v1 import service_pb2 as koloney_dot_koloney_dot_v1_dot_service__pb2


class KoloneyServiceStub(object):
    """KoloneyService provides financial operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBalance = channel.unary_unary(
                '/koloney.koloney.v1.KoloneyService/GetBalance',
                request_serializer=koloney_dot_koloney_dot_v1_dot_service__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=koloney_dot_koloney_dot_v1_dot_service__pb2.GetBalanceResponse.FromString,
                _registered_method=True)


class KoloneyServiceServicer(object):
    """KoloneyService provides financial operations
    """

    def GetBalance(self, request, context):
        """GetBalance retrieves the current balance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KoloneyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=koloney_dot_koloney_dot_v1_dot_service__pb2.GetBalanceRequest.FromString,
                    response_serializer=koloney_dot_koloney_dot_v1_dot_service__pb2.GetBalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'koloney.koloney.v1.KoloneyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('koloney.koloney.v1.KoloneyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KoloneyService(object):
    """KoloneyService provides financial operations
    """

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/koloney.koloney.v1.KoloneyService/GetBalance',
            koloney_dot_koloney_dot_v1_dot_service__pb2.GetBalanceRequest.SerializeToString,
            koloney_dot_koloney_dot_v1_dot_service__pb2.GetBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
