// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: v1/koloney/service.proto

package koloney

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "koloney-protos/go/v1/google/api"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetBalanceRequest is the request for getting balance
type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_v1_koloney_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_koloney_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_v1_koloney_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// GetBalanceResponse is the response containing balance information
type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_v1_koloney_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_koloney_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_v1_koloney_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetBalanceResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_v1_koloney_service_proto protoreflect.FileDescriptor

const file_v1_koloney_service_proto_rawDesc = "" +
	"\n" +
	"\x18v1/koloney/service.proto\x12\x12koloney.v1.koloney\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n" +
	"\x11GetBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\x89\x01\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12=\n" +
	"\flast_updated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated2\x82\x01\n" +
	"\x0eKoloneyService\x12p\n" +
	"\n" +
	"GetBalance\x12%.koloney.v1.koloney.GetBalanceRequest\x1a&.koloney.v1.koloney.GetBalanceResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/balanceB\xb1\x01\n" +
	"\x16com.koloney.v1.koloneyB\fServiceProtoP\x01Z\x1fkoloney-protos/go/v1/v1/koloney\xa2\x02\x03KVK\xaa\x02\x12Koloney.V1.Koloney\xca\x02\x12Koloney\\V1\\Koloney\xe2\x02\x1eKoloney\\V1\\Koloney\\GPBMetadata\xea\x02\x14Koloney::V1::Koloneyb\x06proto3"

var (
	file_v1_koloney_service_proto_rawDescOnce sync.Once
	file_v1_koloney_service_proto_rawDescData []byte
)

func file_v1_koloney_service_proto_rawDescGZIP() []byte {
	file_v1_koloney_service_proto_rawDescOnce.Do(func() {
		file_v1_koloney_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_koloney_service_proto_rawDesc), len(file_v1_koloney_service_proto_rawDesc)))
	})
	return file_v1_koloney_service_proto_rawDescData
}

var file_v1_koloney_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_koloney_service_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),     // 0: koloney.v1.koloney.GetBalanceRequest
	(*GetBalanceResponse)(nil),    // 1: koloney.v1.koloney.GetBalanceResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_v1_koloney_service_proto_depIdxs = []int32{
	2, // 0: koloney.v1.koloney.GetBalanceResponse.last_updated:type_name -> google.protobuf.Timestamp
	0, // 1: koloney.v1.koloney.KoloneyService.GetBalance:input_type -> koloney.v1.koloney.GetBalanceRequest
	1, // 2: koloney.v1.koloney.KoloneyService.GetBalance:output_type -> koloney.v1.koloney.GetBalanceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_koloney_service_proto_init() }
func file_v1_koloney_service_proto_init() {
	if File_v1_koloney_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_koloney_service_proto_rawDesc), len(file_v1_koloney_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_koloney_service_proto_goTypes,
		DependencyIndexes: file_v1_koloney_service_proto_depIdxs,
		MessageInfos:      file_v1_koloney_service_proto_msgTypes,
	}.Build()
	File_v1_koloney_service_proto = out.File
	file_v1_koloney_service_proto_goTypes = nil
	file_v1_koloney_service_proto_depIdxs = nil
}
