// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: koloney/user/v1/entities.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "koloney-protos/go/v1/google/api"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserStatus represents the possible states of a user account.
type UserStatus int32

const (
	// The user status is unspecified.
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	// The user account is active.
	UserStatus_USER_STATUS_ACTIVE UserStatus = 1
	// The user account is suspended.
	UserStatus_USER_STATUS_SUSPENDED UserStatus = 2
	// The user account is deleted.
	UserStatus_USER_STATUS_DELETED UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_ACTIVE",
		2: "USER_STATUS_SUSPENDED",
		3: "USER_STATUS_DELETED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_ACTIVE":      1,
		"USER_STATUS_SUSPENDED":   2,
		"USER_STATUS_DELETED":     3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_koloney_user_v1_entities_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_koloney_user_v1_entities_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_koloney_user_v1_entities_proto_rawDescGZIP(), []int{0}
}

// User represents a user account in the Koloney system.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the user.
	// Format: `users/{user}`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The unique identifier of the user.
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// The user's email address.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// The user's display name.
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The user's profile picture URL.
	AvatarUrl *string `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	// The user's account status.
	Status UserStatus `protobuf:"varint,6,opt,name=status,proto3,enum=koloney.user.v1.UserStatus" json:"status,omitempty"`
	// The user's preferences.
	Preferences *UserPreferences `protobuf:"bytes,7,opt,name=preferences,proto3" json:"preferences,omitempty"`
	// The creation timestamp of the user.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last update timestamp of the user.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// The last login timestamp of the user.
	LastLoginTime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_koloney_user_v1_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_user_v1_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_koloney_user_v1_entities_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *User) GetPreferences() *UserPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *User) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *User) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *User) GetLastLoginTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginTime
	}
	return nil
}

// UserPreferences contains user-specific settings.
type UserPreferences struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether email notifications are enabled.
	EmailNotificationsEnabled bool `protobuf:"varint,1,opt,name=email_notifications_enabled,json=emailNotificationsEnabled,proto3" json:"email_notifications_enabled,omitempty"`
	// The preferred language code (e.g., "en-US").
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// The theme preference (light/dark).
	Theme string `protobuf:"bytes,3,opt,name=theme,proto3" json:"theme,omitempty"`
	// The time zone (e.g., "America/New_York").
	Timezone      string `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPreferences) Reset() {
	*x = UserPreferences{}
	mi := &file_koloney_user_v1_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferences) ProtoMessage() {}

func (x *UserPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_user_v1_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferences.ProtoReflect.Descriptor instead.
func (*UserPreferences) Descriptor() ([]byte, []int) {
	return file_koloney_user_v1_entities_proto_rawDescGZIP(), []int{1}
}

func (x *UserPreferences) GetEmailNotificationsEnabled() bool {
	if x != nil {
		return x.EmailNotificationsEnabled
	}
	return false
}

func (x *UserPreferences) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserPreferences) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *UserPreferences) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

var File_koloney_user_v1_entities_proto protoreflect.FileDescriptor

const file_koloney_user_v1_entities_proto_rawDesc = "" +
	"\n" +
	"\x1ekoloney/user/v1/entities.proto\x12\x0fkoloney.user.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x04\n" +
	"\x04User\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12\x15\n" +
	"\x03uid\x18\x02 \x01(\tB\x03\xe0A\x03R\x03uid\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tB\x03\xe0A\x02R\x05email\x12&\n" +
	"\fdisplay_name\x18\x04 \x01(\tB\x03\xe0A\x02R\vdisplayName\x12\"\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tH\x00R\tavatarUrl\x88\x01\x01\x128\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1b.koloney.user.v1.UserStatusB\x03\xe0A\x03R\x06status\x12B\n" +
	"\vpreferences\x18\a \x01(\v2 .koloney.user.v1.UserPreferencesR\vpreferences\x12@\n" +
	"\vcreate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12G\n" +
	"\x0flast_login_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\rlastLoginTime:.\xeaA+\n" +
	"\x1bkoloney.googleapis.com/User\x12\fusers/{user}B\r\n" +
	"\v_avatar_url\"\x9f\x01\n" +
	"\x0fUserPreferences\x12>\n" +
	"\x1bemail_notifications_enabled\x18\x01 \x01(\bR\x19emailNotificationsEnabled\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x14\n" +
	"\x05theme\x18\x03 \x01(\tR\x05theme\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone*u\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15USER_STATUS_SUSPENDED\x10\x02\x12\x17\n" +
	"\x13USER_STATUS_DELETED\x10\x03B\xaf\x01\n" +
	"\x13com.koloney.user.v1B\rEntitiesProtoP\x01Z+koloney-protos/go/v1/koloney/user/v1;userv1\xa2\x02\x03KUX\xaa\x02\x0fKoloney.User.V1\xca\x02\x0fKoloney\\User\\V1\xe2\x02\x1bKoloney\\User\\V1\\GPBMetadata\xea\x02\x11Koloney::User::V1b\x06proto3"

var (
	file_koloney_user_v1_entities_proto_rawDescOnce sync.Once
	file_koloney_user_v1_entities_proto_rawDescData []byte
)

func file_koloney_user_v1_entities_proto_rawDescGZIP() []byte {
	file_koloney_user_v1_entities_proto_rawDescOnce.Do(func() {
		file_koloney_user_v1_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_koloney_user_v1_entities_proto_rawDesc), len(file_koloney_user_v1_entities_proto_rawDesc)))
	})
	return file_koloney_user_v1_entities_proto_rawDescData
}

var file_koloney_user_v1_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_koloney_user_v1_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_koloney_user_v1_entities_proto_goTypes = []any{
	(UserStatus)(0),               // 0: koloney.user.v1.UserStatus
	(*User)(nil),                  // 1: koloney.user.v1.User
	(*UserPreferences)(nil),       // 2: koloney.user.v1.UserPreferences
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_koloney_user_v1_entities_proto_depIdxs = []int32{
	0, // 0: koloney.user.v1.User.status:type_name -> koloney.user.v1.UserStatus
	2, // 1: koloney.user.v1.User.preferences:type_name -> koloney.user.v1.UserPreferences
	3, // 2: koloney.user.v1.User.create_time:type_name -> google.protobuf.Timestamp
	3, // 3: koloney.user.v1.User.update_time:type_name -> google.protobuf.Timestamp
	3, // 4: koloney.user.v1.User.last_login_time:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_koloney_user_v1_entities_proto_init() }
func file_koloney_user_v1_entities_proto_init() {
	if File_koloney_user_v1_entities_proto != nil {
		return
	}
	file_koloney_user_v1_entities_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_koloney_user_v1_entities_proto_rawDesc), len(file_koloney_user_v1_entities_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_koloney_user_v1_entities_proto_goTypes,
		DependencyIndexes: file_koloney_user_v1_entities_proto_depIdxs,
		EnumInfos:         file_koloney_user_v1_entities_proto_enumTypes,
		MessageInfos:      file_koloney_user_v1_entities_proto_msgTypes,
	}.Build()
	File_koloney_user_v1_entities_proto = out.File
	file_koloney_user_v1_entities_proto_goTypes = nil
	file_koloney_user_v1_entities_proto_depIdxs = nil
}
