// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: koloney/user/v1/service.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "koloney-protos/go/v1/google/api"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateUserRequest contains the information needed to create a new user.
type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user resource to create.
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// The user's password.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_koloney_user_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_user_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_koloney_user_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// GetUserRequest contains the name of the user to retrieve.
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the user to retrieve.
	// Format: `users/{user}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_koloney_user_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_user_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_koloney_user_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// UpdateUserRequest contains the fields that can be updated for a user.
type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user resource which replaces the resource on the server.
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// The list of fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_koloney_user_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_user_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_koloney_user_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// DeleteUserRequest contains the name of the user to delete.
type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the user to delete.
	// Format: `users/{user}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_koloney_user_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_user_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_koloney_user_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListUsersRequest contains pagination parameters.
type ListUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of users to return.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token value returned from a previous List request, if any.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter users by status.
	Status        *UserStatus `protobuf:"varint,3,opt,name=status,proto3,enum=koloney.user.v1.UserStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_koloney_user_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_user_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_koloney_user_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListUsersRequest) GetStatus() UserStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

// ListUsersResponse contains a page of users and pagination info.
type ListUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of users.
	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// Token to retrieve the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// The total number of users matching the request.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_koloney_user_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_user_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_koloney_user_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListUsersResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// AuthenticateUserRequest contains login credentials.
type AuthenticateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's email address.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// The user's password.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateUserRequest) Reset() {
	*x = AuthenticateUserRequest{}
	mi := &file_koloney_user_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateUserRequest) ProtoMessage() {}

func (x *AuthenticateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_user_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateUserRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) {
	return file_koloney_user_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *AuthenticateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthenticateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// AuthenticateUserResponse contains authentication result.
type AuthenticateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The authenticated user.
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// The access token for the user.
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// The expiration timestamp of the access token.
	ExpiresTime   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_time,json=expiresTime,proto3" json:"expires_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateUserResponse) Reset() {
	*x = AuthenticateUserResponse{}
	mi := &file_koloney_user_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateUserResponse) ProtoMessage() {}

func (x *AuthenticateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_user_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateUserResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateUserResponse) Descriptor() ([]byte, []int) {
	return file_koloney_user_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *AuthenticateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthenticateUserResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthenticateUserResponse) GetExpiresTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresTime
	}
	return nil
}

// CreateUserResponse contains the created user.
type CreateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created user.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_koloney_user_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_user_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_koloney_user_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// GetUserResponse contains the retrieved user.
type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The retrieved user.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_koloney_user_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_user_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_koloney_user_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// UpdateUserResponse contains the updated user.
type UpdateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated user.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_koloney_user_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_user_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_koloney_user_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// DeleteUserResponse indicates successful deletion.
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_koloney_user_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koloney_user_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_koloney_user_v1_service_proto_rawDescGZIP(), []int{11}
}

var File_koloney_user_v1_service_proto protoreflect.FileDescriptor

const file_koloney_user_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dkoloney/user/v1/service.proto\x12\x0fkoloney.user.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ekoloney/user/v1/entities.proto\"d\n" +
	"\x11CreateUserRequest\x12.\n" +
	"\x04user\x18\x01 \x01(\v2\x15.koloney.user.v1.UserB\x03\xe0A\x02R\x04user\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tB\x03\xe0A\x02R\bpassword\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"\x80\x01\n" +
	"\x11UpdateUserRequest\x12.\n" +
	"\x04user\x18\x01 \x01(\v2\x15.koloney.user.v1.UserB\x03\xe0A\x02R\x04user\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"\x93\x01\n" +
	"\x10ListUsersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x128\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.koloney.user.v1.UserStatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\x87\x01\n" +
	"\x11ListUsersResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.koloney.user.v1.UserR\x05users\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"U\n" +
	"\x17AuthenticateUserRequest\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tB\x03\xe0A\x02R\x05email\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tB\x03\xe0A\x02R\bpassword\"\xa7\x01\n" +
	"\x18AuthenticateUserResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.koloney.user.v1.UserR\x04user\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12=\n" +
	"\fexpires_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vexpiresTime\"?\n" +
	"\x12CreateUserResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.koloney.user.v1.UserR\x04user\"<\n" +
	"\x0fGetUserResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.koloney.user.v1.UserR\x04user\"?\n" +
	"\x12UpdateUserResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.koloney.user.v1.UserR\x04user\"\x14\n" +
	"\x12DeleteUserResponse2\xcc\x05\n" +
	"\vUserService\x12n\n" +
	"\n" +
	"CreateUser\x12\".koloney.user.v1.CreateUserRequest\x1a#.koloney.user.v1.CreateUserResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x04user\"\t/v1/users\x12h\n" +
	"\aGetUser\x12\x1f.koloney.user.v1.GetUserRequest\x1a .koloney.user.v1.GetUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/{name=users/*}\x12|\n" +
	"\n" +
	"UpdateUser\x12\".koloney.user.v1.UpdateUserRequest\x1a#.koloney.user.v1.UpdateUserResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x04user2\x17/v1/{user.name=users/*}\x12q\n" +
	"\n" +
	"DeleteUser\x12\".koloney.user.v1.DeleteUserRequest\x1a#.koloney.user.v1.DeleteUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/{name=users/*}\x12e\n" +
	"\tListUsers\x12!.koloney.user.v1.ListUsersRequest\x1a\".koloney.user.v1.ListUsersResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12\x8a\x01\n" +
	"\x10AuthenticateUser\x12(.koloney.user.v1.AuthenticateUserRequest\x1a).koloney.user.v1.AuthenticateUserResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/users:authenticateB\xae\x01\n" +
	"\x13com.koloney.user.v1B\fServiceProtoP\x01Z+koloney-protos/go/v1/koloney/user/v1;userv1\xa2\x02\x03KUX\xaa\x02\x0fKoloney.User.V1\xca\x02\x0fKoloney\\User\\V1\xe2\x02\x1bKoloney\\User\\V1\\GPBMetadata\xea\x02\x11Koloney::User::V1b\x06proto3"

var (
	file_koloney_user_v1_service_proto_rawDescOnce sync.Once
	file_koloney_user_v1_service_proto_rawDescData []byte
)

func file_koloney_user_v1_service_proto_rawDescGZIP() []byte {
	file_koloney_user_v1_service_proto_rawDescOnce.Do(func() {
		file_koloney_user_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_koloney_user_v1_service_proto_rawDesc), len(file_koloney_user_v1_service_proto_rawDesc)))
	})
	return file_koloney_user_v1_service_proto_rawDescData
}

var file_koloney_user_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_koloney_user_v1_service_proto_goTypes = []any{
	(*CreateUserRequest)(nil),        // 0: koloney.user.v1.CreateUserRequest
	(*GetUserRequest)(nil),           // 1: koloney.user.v1.GetUserRequest
	(*UpdateUserRequest)(nil),        // 2: koloney.user.v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),        // 3: koloney.user.v1.DeleteUserRequest
	(*ListUsersRequest)(nil),         // 4: koloney.user.v1.ListUsersRequest
	(*ListUsersResponse)(nil),        // 5: koloney.user.v1.ListUsersResponse
	(*AuthenticateUserRequest)(nil),  // 6: koloney.user.v1.AuthenticateUserRequest
	(*AuthenticateUserResponse)(nil), // 7: koloney.user.v1.AuthenticateUserResponse
	(*CreateUserResponse)(nil),       // 8: koloney.user.v1.CreateUserResponse
	(*GetUserResponse)(nil),          // 9: koloney.user.v1.GetUserResponse
	(*UpdateUserResponse)(nil),       // 10: koloney.user.v1.UpdateUserResponse
	(*DeleteUserResponse)(nil),       // 11: koloney.user.v1.DeleteUserResponse
	(*User)(nil),                     // 12: koloney.user.v1.User
	(*fieldmaskpb.FieldMask)(nil),    // 13: google.protobuf.FieldMask
	(UserStatus)(0),                  // 14: koloney.user.v1.UserStatus
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_koloney_user_v1_service_proto_depIdxs = []int32{
	12, // 0: koloney.user.v1.CreateUserRequest.user:type_name -> koloney.user.v1.User
	12, // 1: koloney.user.v1.UpdateUserRequest.user:type_name -> koloney.user.v1.User
	13, // 2: koloney.user.v1.UpdateUserRequest.update_mask:type_name -> google.protobuf.FieldMask
	14, // 3: koloney.user.v1.ListUsersRequest.status:type_name -> koloney.user.v1.UserStatus
	12, // 4: koloney.user.v1.ListUsersResponse.users:type_name -> koloney.user.v1.User
	12, // 5: koloney.user.v1.AuthenticateUserResponse.user:type_name -> koloney.user.v1.User
	15, // 6: koloney.user.v1.AuthenticateUserResponse.expires_time:type_name -> google.protobuf.Timestamp
	12, // 7: koloney.user.v1.CreateUserResponse.user:type_name -> koloney.user.v1.User
	12, // 8: koloney.user.v1.GetUserResponse.user:type_name -> koloney.user.v1.User
	12, // 9: koloney.user.v1.UpdateUserResponse.user:type_name -> koloney.user.v1.User
	0,  // 10: koloney.user.v1.UserService.CreateUser:input_type -> koloney.user.v1.CreateUserRequest
	1,  // 11: koloney.user.v1.UserService.GetUser:input_type -> koloney.user.v1.GetUserRequest
	2,  // 12: koloney.user.v1.UserService.UpdateUser:input_type -> koloney.user.v1.UpdateUserRequest
	3,  // 13: koloney.user.v1.UserService.DeleteUser:input_type -> koloney.user.v1.DeleteUserRequest
	4,  // 14: koloney.user.v1.UserService.ListUsers:input_type -> koloney.user.v1.ListUsersRequest
	6,  // 15: koloney.user.v1.UserService.AuthenticateUser:input_type -> koloney.user.v1.AuthenticateUserRequest
	8,  // 16: koloney.user.v1.UserService.CreateUser:output_type -> koloney.user.v1.CreateUserResponse
	9,  // 17: koloney.user.v1.UserService.GetUser:output_type -> koloney.user.v1.GetUserResponse
	10, // 18: koloney.user.v1.UserService.UpdateUser:output_type -> koloney.user.v1.UpdateUserResponse
	11, // 19: koloney.user.v1.UserService.DeleteUser:output_type -> koloney.user.v1.DeleteUserResponse
	5,  // 20: koloney.user.v1.UserService.ListUsers:output_type -> koloney.user.v1.ListUsersResponse
	7,  // 21: koloney.user.v1.UserService.AuthenticateUser:output_type -> koloney.user.v1.AuthenticateUserResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_koloney_user_v1_service_proto_init() }
func file_koloney_user_v1_service_proto_init() {
	if File_koloney_user_v1_service_proto != nil {
		return
	}
	file_koloney_user_v1_entities_proto_init()
	file_koloney_user_v1_service_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_koloney_user_v1_service_proto_rawDesc), len(file_koloney_user_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_koloney_user_v1_service_proto_goTypes,
		DependencyIndexes: file_koloney_user_v1_service_proto_depIdxs,
		MessageInfos:      file_koloney_user_v1_service_proto_msgTypes,
	}.Build()
	File_koloney_user_v1_service_proto = out.File
	file_koloney_user_v1_service_proto_goTypes = nil
	file_koloney_user_v1_service_proto_depIdxs = nil
}
