// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file v1/proto/user/entities.proto (package user, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/proto/user/entities.proto.
 */
export const file_v1_proto_user_entities: GenFile = /*@__PURE__*/
  fileDesc("Chx2MS9wcm90by91c2VyL2VudGl0aWVzLnByb3RvEgR1c2VyIqcCCgRVc2VyEgoKAmlkGAEgASgJEg0KBWVtYWlsGAIgASgJEhQKDGRpc3BsYXlfbmFtZRgDIAEoCRIVCg1wYXNzd29yZF9oYXNoGAQgASgJEhcKCmF2YXRhcl91cmwYBSABKAlIAIgBARIgCgZzdGF0dXMYBiABKA4yEC51c2VyLlVzZXJTdGF0dXMSLgoKY3JlYXRlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASMQoNbGFzdF9sb2dpbl9hdBgIIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASKgoLcHJlZmVyZW5jZXMYCSABKAsyFS51c2VyLlVzZXJQcmVmZXJlbmNlc0INCgtfYXZhdGFyX3VybCJpCg9Vc2VyUHJlZmVyZW5jZXMSIwobZW1haWxfbm90aWZpY2F0aW9uc19lbmFibGVkGAEgASgIEhAKCGxhbmd1YWdlGAIgASgJEg0KBXRoZW1lGAMgASgJEhAKCHRpbWV6b25lGAQgASgJKnUKClVzZXJTdGF0dXMSGwoXVVNFUl9TVEFUVVNfVU5TUEVDSUZJRUQQABIWChJVU0VSX1NUQVRVU19BQ1RJVkUQARIZChVVU0VSX1NUQVRVU19TVVNQRU5ERUQQAhIXChNVU0VSX1NUQVRVU19ERUxFVEVEEANCbQoIY29tLnVzZXJCDUVudGl0aWVzUHJvdG9QAVoia29sb25leS1wcm90b3MvdjEvZ28vdjEvcHJvdG8vdXNlcqICA1VYWKoCBFVzZXLKAgRVc2Vy4gIQVXNlclxHUEJNZXRhZGF0YeoCBFVzZXJiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * User represents a user account in the Koloney system
 *
 * @generated from message user.User
 */
export type User = Message<"user.User"> & {
  /**
   * Unique identifier for the user
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * User's email address
   *
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * User's display name
   *
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * Hashed password
   *
   * @generated from field: string password_hash = 4;
   */
  passwordHash: string;

  /**
   * User's profile picture URL
   *
   * @generated from field: optional string avatar_url = 5;
   */
  avatarUrl?: string;

  /**
   * Account status (active, suspended, etc)
   *
   * @generated from field: user.UserStatus status = 6;
   */
  status: UserStatus;

  /**
   * When the user account was created
   *
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp;

  /**
   * When the user last logged in
   *
   * @generated from field: google.protobuf.Timestamp last_login_at = 8;
   */
  lastLoginAt?: Timestamp;

  /**
   * User's preferences/settings
   *
   * @generated from field: user.UserPreferences preferences = 9;
   */
  preferences?: UserPreferences;
};

/**
 * Describes the message user.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_v1_proto_user_entities, 0);

/**
 * UserPreferences contains user-specific settings
 *
 * @generated from message user.UserPreferences
 */
export type UserPreferences = Message<"user.UserPreferences"> & {
  /**
   * Email notification preferences
   *
   * @generated from field: bool email_notifications_enabled = 1;
   */
  emailNotificationsEnabled: boolean;

  /**
   * Preferred language code (e.g., "en-US")
   *
   * @generated from field: string language = 2;
   */
  language: string;

  /**
   * Theme preference (light/dark)
   *
   * @generated from field: string theme = 3;
   */
  theme: string;

  /**
   * Time zone (e.g., "America/New_York") 
   *
   * @generated from field: string timezone = 4;
   */
  timezone: string;
};

/**
 * Describes the message user.UserPreferences.
 * Use `create(UserPreferencesSchema)` to create a new message.
 */
export const UserPreferencesSchema: GenMessage<UserPreferences> = /*@__PURE__*/
  messageDesc(file_v1_proto_user_entities, 1);

/**
 * UserStatus represents the possible states of a user account
 *
 * @generated from enum user.UserStatus
 */
export enum UserStatus {
  /**
   * @generated from enum value: USER_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: USER_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: USER_STATUS_SUSPENDED = 2;
   */
  SUSPENDED = 2,

  /**
   * @generated from enum value: USER_STATUS_DELETED = 3;
   */
  DELETED = 3,
}

/**
 * Describes the enum user.UserStatus.
 */
export const UserStatusSchema: GenEnum<UserStatus> = /*@__PURE__*/
  enumDesc(file_v1_proto_user_entities, 0);

