// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file v1/proto/user/service.proto (package user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AuthenticateUserRequest, AuthenticateUserResponse, ChangePasswordRequest, CreateUserRequest, DeleteUserRequest, GetUserRequest, ListUsersRequest, ListUsersResponse, UpdateUserRequest } from "./service_pb.js";
import { User } from "./entities_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * UserService provides user management functionality
 *
 * @generated from service user.UserService
 */
export const UserService = {
  typeName: "user.UserService",
  methods: {
    /**
     * CreateUser creates a new user account
     *
     * @generated from rpc user.UserService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * GetUser retrieves a user by ID
     *
     * @generated from rpc user.UserService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateUser updates an existing user's information
     *
     * @generated from rpc user.UserService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteUser marks a user account as deleted
     *
     * @generated from rpc user.UserService.DeleteUser
     */
    deleteUser: {
      name: "DeleteUser",
      I: DeleteUserRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * ListUsers retrieves a paginated list of users
     *
     * @generated from rpc user.UserService.ListUsers
     */
    listUsers: {
      name: "ListUsers",
      I: ListUsersRequest,
      O: ListUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * AuthenticateUser validates user credentials and returns user info
     *
     * @generated from rpc user.UserService.AuthenticateUser
     */
    authenticateUser: {
      name: "AuthenticateUser",
      I: AuthenticateUserRequest,
      O: AuthenticateUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ChangePassword allows users to update their password
     *
     * @generated from rpc user.UserService.ChangePassword
     */
    changePassword: {
      name: "ChangePassword",
      I: ChangePasswordRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

