// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file v1/proto/payment/entities.proto (package payment, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/proto/payment/entities.proto.
 */
export const file_v1_proto_payment_entities: GenFile = /*@__PURE__*/
  fileDesc("Ch92MS9wcm90by9wYXltZW50L2VudGl0aWVzLnByb3RvEgdwYXltZW50IpYDCgdQYXltZW50EgoKAmlkGAEgASgJEg8KB3VzZXJfaWQYAiABKAkSEgoKY29tcGFueV9pZBgDIAEoCRIiCgR0eXBlGAQgASgOMhQucGF5bWVudC5QYXltZW50VHlwZRImCgZzdGF0dXMYBSABKA4yFi5wYXltZW50LlBheW1lbnRTdGF0dXMSJgoGbWV0aG9kGAYgASgOMhYucGF5bWVudC5QYXltZW50TWV0aG9kEiYKBmFtb3VudBgHIAEoCzIWLnBheW1lbnQuUGF5bWVudEFtb3VudBIqCghtZXRhZGF0YRgIIAEoCzIYLnBheW1lbnQuUGF5bWVudE1ldGFkYXRhEi4KCmNyZWF0ZWRfYXQYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjAKDHByb2Nlc3NlZF9hdBgKIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASMAoMY29tcGxldGVkX2F0GAsgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJ0Cg1QYXltZW50QW1vdW50Eg4KBmFtb3VudBgBIAEoARIQCghjdXJyZW5jeRgCIAEoCRISCgp0YXhfYW1vdW50GAMgASgBEhcKD2Rpc2NvdW50X2Ftb3VudBgEIAEoARIUCgx0b3RhbF9hbW91bnQYBSABKAEiYAoPUGF5bWVudE1ldGFkYXRhEhMKC2Rlc2NyaXB0aW9uGAEgASgJEhIKCmludm9pY2VfaWQYAiABKAkSFgoOdHJhbnNhY3Rpb25faWQYAyABKAkSDAoEdGFncxgEIAMoCSqkAQoLUGF5bWVudFR5cGUSHAoYUEFZTUVOVF9UWVBFX1VOU1BFQ0lGSUVEEAASHQoZUEFZTUVOVF9UWVBFX1NVQlNDUklQVElPThABEhwKGFBBWU1FTlRfVFlQRV9KT0JfUE9TVElORxACEiEKHVBBWU1FTlRfVFlQRV9QUkVNSVVNX0ZFQVRVUkVTEAMSFwoTUEFZTUVOVF9UWVBFX1JFRlVORBAEKt4BCg1QYXltZW50U3RhdHVzEh4KGlBBWU1FTlRfU1RBVFVTX1VOU1BFQ0lGSUVEEAASGgoWUEFZTUVOVF9TVEFUVVNfUEVORElORxABEh0KGVBBWU1FTlRfU1RBVFVTX1BST0NFU1NJTkcQAhIcChhQQVlNRU5UX1NUQVRVU19DT01QTEVURUQQAxIZChVQQVlNRU5UX1NUQVRVU19GQUlMRUQQBBIcChhQQVlNRU5UX1NUQVRVU19DQU5DRUxMRUQQBRIbChdQQVlNRU5UX1NUQVRVU19SRUZVTkRFRBAGKsYBCg1QYXltZW50TWV0aG9kEh4KGlBBWU1FTlRfTUVUSE9EX1VOU1BFQ0lGSUVEEAASHgoaUEFZTUVOVF9NRVRIT0RfQ1JFRElUX0NBUkQQARIdChlQQVlNRU5UX01FVEhPRF9ERUJJVF9DQVJEEAISIAocUEFZTUVOVF9NRVRIT0RfQkFOS19UUkFOU0ZFUhADEhkKFVBBWU1FTlRfTUVUSE9EX1BBWVBBTBAEEhkKFVBBWU1FTlRfTUVUSE9EX1NUUklQRRAFQn8KC2NvbS5wYXltZW50Qg1FbnRpdGllc1Byb3RvUAFaJWtvbG9uZXktcHJvdG9zL3YxL2dvL3YxL3Byb3RvL3BheW1lbnSiAgNQWFiqAgdQYXltZW50ygIHUGF5bWVudOICE1BheW1lbnRcR1BCTWV0YWRhdGHqAgdQYXltZW50YgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Payment represents a financial transaction
 *
 * @generated from message payment.Payment
 */
export type Payment = Message<"payment.Payment"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string company_id = 3;
   */
  companyId: string;

  /**
   * @generated from field: payment.PaymentType type = 4;
   */
  type: PaymentType;

  /**
   * @generated from field: payment.PaymentStatus status = 5;
   */
  status: PaymentStatus;

  /**
   * @generated from field: payment.PaymentMethod method = 6;
   */
  method: PaymentMethod;

  /**
   * @generated from field: payment.PaymentAmount amount = 7;
   */
  amount?: PaymentAmount;

  /**
   * @generated from field: payment.PaymentMetadata metadata = 8;
   */
  metadata?: PaymentMetadata;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 9;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp processed_at = 10;
   */
  processedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp completed_at = 11;
   */
  completedAt?: Timestamp;
};

/**
 * Describes the message payment.Payment.
 * Use `create(PaymentSchema)` to create a new message.
 */
export const PaymentSchema: GenMessage<Payment> = /*@__PURE__*/
  messageDesc(file_v1_proto_payment_entities, 0);

/**
 * PaymentAmount represents the monetary amount
 *
 * @generated from message payment.PaymentAmount
 */
export type PaymentAmount = Message<"payment.PaymentAmount"> & {
  /**
   * @generated from field: double amount = 1;
   */
  amount: number;

  /**
   * @generated from field: string currency = 2;
   */
  currency: string;

  /**
   * @generated from field: double tax_amount = 3;
   */
  taxAmount: number;

  /**
   * @generated from field: double discount_amount = 4;
   */
  discountAmount: number;

  /**
   * @generated from field: double total_amount = 5;
   */
  totalAmount: number;
};

/**
 * Describes the message payment.PaymentAmount.
 * Use `create(PaymentAmountSchema)` to create a new message.
 */
export const PaymentAmountSchema: GenMessage<PaymentAmount> = /*@__PURE__*/
  messageDesc(file_v1_proto_payment_entities, 1);

/**
 * PaymentMetadata represents additional information
 *
 * @generated from message payment.PaymentMetadata
 */
export type PaymentMetadata = Message<"payment.PaymentMetadata"> & {
  /**
   * @generated from field: string description = 1;
   */
  description: string;

  /**
   * @generated from field: string invoice_id = 2;
   */
  invoiceId: string;

  /**
   * @generated from field: string transaction_id = 3;
   */
  transactionId: string;

  /**
   * @generated from field: repeated string tags = 4;
   */
  tags: string[];
};

/**
 * Describes the message payment.PaymentMetadata.
 * Use `create(PaymentMetadataSchema)` to create a new message.
 */
export const PaymentMetadataSchema: GenMessage<PaymentMetadata> = /*@__PURE__*/
  messageDesc(file_v1_proto_payment_entities, 2);

/**
 * PaymentType represents the type of payment
 *
 * @generated from enum payment.PaymentType
 */
export enum PaymentType {
  /**
   * @generated from enum value: PAYMENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PAYMENT_TYPE_SUBSCRIPTION = 1;
   */
  SUBSCRIPTION = 1,

  /**
   * @generated from enum value: PAYMENT_TYPE_JOB_POSTING = 2;
   */
  JOB_POSTING = 2,

  /**
   * @generated from enum value: PAYMENT_TYPE_PREMIUM_FEATURES = 3;
   */
  PREMIUM_FEATURES = 3,

  /**
   * @generated from enum value: PAYMENT_TYPE_REFUND = 4;
   */
  REFUND = 4,
}

/**
 * Describes the enum payment.PaymentType.
 */
export const PaymentTypeSchema: GenEnum<PaymentType> = /*@__PURE__*/
  enumDesc(file_v1_proto_payment_entities, 0);

/**
 * PaymentStatus represents the current status
 *
 * @generated from enum payment.PaymentStatus
 */
export enum PaymentStatus {
  /**
   * @generated from enum value: PAYMENT_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PAYMENT_STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: PAYMENT_STATUS_PROCESSING = 2;
   */
  PROCESSING = 2,

  /**
   * @generated from enum value: PAYMENT_STATUS_COMPLETED = 3;
   */
  COMPLETED = 3,

  /**
   * @generated from enum value: PAYMENT_STATUS_FAILED = 4;
   */
  FAILED = 4,

  /**
   * @generated from enum value: PAYMENT_STATUS_CANCELLED = 5;
   */
  CANCELLED = 5,

  /**
   * @generated from enum value: PAYMENT_STATUS_REFUNDED = 6;
   */
  REFUNDED = 6,
}

/**
 * Describes the enum payment.PaymentStatus.
 */
export const PaymentStatusSchema: GenEnum<PaymentStatus> = /*@__PURE__*/
  enumDesc(file_v1_proto_payment_entities, 1);

/**
 * PaymentMethod represents how payment is made
 *
 * @generated from enum payment.PaymentMethod
 */
export enum PaymentMethod {
  /**
   * @generated from enum value: PAYMENT_METHOD_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PAYMENT_METHOD_CREDIT_CARD = 1;
   */
  CREDIT_CARD = 1,

  /**
   * @generated from enum value: PAYMENT_METHOD_DEBIT_CARD = 2;
   */
  DEBIT_CARD = 2,

  /**
   * @generated from enum value: PAYMENT_METHOD_BANK_TRANSFER = 3;
   */
  BANK_TRANSFER = 3,

  /**
   * @generated from enum value: PAYMENT_METHOD_PAYPAL = 4;
   */
  PAYPAL = 4,

  /**
   * @generated from enum value: PAYMENT_METHOD_STRIPE = 5;
   */
  STRIPE = 5,
}

/**
 * Describes the enum payment.PaymentMethod.
 */
export const PaymentMethodSchema: GenEnum<PaymentMethod> = /*@__PURE__*/
  enumDesc(file_v1_proto_payment_entities, 2);

