// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file v1/proto/company/company.proto (package koloney.company.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Company, CreateCompanyRequest, DeleteCompanyRequest, GetCompanyRequest, ListCompaniesRequest, ListCompaniesResponse, SearchCompaniesRequest, SearchCompaniesResponse, UpdateCompanyRequest, UpdateCompanyStatusRequest, VerifyCompanyRequest } from "./company_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * CompanyService provides company management functionality.
 *
 * @generated from service koloney.company.v1.CompanyService
 */
export const CompanyService = {
  typeName: "koloney.company.v1.CompanyService",
  methods: {
    /**
     * CreateCompany creates a new company profile.
     *
     * @generated from rpc koloney.company.v1.CompanyService.CreateCompany
     */
    createCompany: {
      name: "CreateCompany",
      I: CreateCompanyRequest,
      O: Company,
      kind: MethodKind.Unary,
    },
    /**
     * GetCompany retrieves a company by name.
     *
     * @generated from rpc koloney.company.v1.CompanyService.GetCompany
     */
    getCompany: {
      name: "GetCompany",
      I: GetCompanyRequest,
      O: Company,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateCompany updates an existing company profile.
     *
     * @generated from rpc koloney.company.v1.CompanyService.UpdateCompany
     */
    updateCompany: {
      name: "UpdateCompany",
      I: UpdateCompanyRequest,
      O: Company,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteCompany removes a company profile.
     *
     * @generated from rpc koloney.company.v1.CompanyService.DeleteCompany
     */
    deleteCompany: {
      name: "DeleteCompany",
      I: DeleteCompanyRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * ListCompanies retrieves a paginated list of companies.
     *
     * @generated from rpc koloney.company.v1.CompanyService.ListCompanies
     */
    listCompanies: {
      name: "ListCompanies",
      I: ListCompaniesRequest,
      O: ListCompaniesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * SearchCompanies searches for companies based on criteria.
     *
     * @generated from rpc koloney.company.v1.CompanyService.SearchCompanies
     */
    searchCompanies: {
      name: "SearchCompanies",
      I: SearchCompaniesRequest,
      O: SearchCompaniesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateCompanyStatus changes the status of a company.
     *
     * @generated from rpc koloney.company.v1.CompanyService.UpdateCompanyStatus
     */
    updateCompanyStatus: {
      name: "UpdateCompanyStatus",
      I: UpdateCompanyStatusRequest,
      O: Company,
      kind: MethodKind.Unary,
    },
    /**
     * VerifyCompany marks a company as verified.
     *
     * @generated from rpc koloney.company.v1.CompanyService.VerifyCompany
     */
    verifyCompany: {
      name: "VerifyCompany",
      I: VerifyCompanyRequest,
      O: Company,
      kind: MethodKind.Unary,
    },
  }
} as const;

