// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file v1/proto/application/application.proto (package koloney.application.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Application, CreateApplicationRequest, DeleteApplicationRequest, GetApplicationRequest, ListApplicationsRequest, ListApplicationsResponse, UpdateApplicationRequest, UpdateApplicationStatusRequest } from "./application_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * ApplicationService provides application management functionality.
 *
 * @generated from service koloney.application.v1.ApplicationService
 */
export const ApplicationService = {
  typeName: "koloney.application.v1.ApplicationService",
  methods: {
    /**
     * CreateApplication creates a new job application.
     *
     * @generated from rpc koloney.application.v1.ApplicationService.CreateApplication
     */
    createApplication: {
      name: "CreateApplication",
      I: CreateApplicationRequest,
      O: Application,
      kind: MethodKind.Unary,
    },
    /**
     * GetApplication retrieves an application by name.
     *
     * @generated from rpc koloney.application.v1.ApplicationService.GetApplication
     */
    getApplication: {
      name: "GetApplication",
      I: GetApplicationRequest,
      O: Application,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateApplication updates an existing application.
     *
     * @generated from rpc koloney.application.v1.ApplicationService.UpdateApplication
     */
    updateApplication: {
      name: "UpdateApplication",
      I: UpdateApplicationRequest,
      O: Application,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteApplication removes an application.
     *
     * @generated from rpc koloney.application.v1.ApplicationService.DeleteApplication
     */
    deleteApplication: {
      name: "DeleteApplication",
      I: DeleteApplicationRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * ListApplications retrieves a paginated list of applications.
     *
     * @generated from rpc koloney.application.v1.ApplicationService.ListApplications
     */
    listApplications: {
      name: "ListApplications",
      I: ListApplicationsRequest,
      O: ListApplicationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateApplicationStatus changes the status of an application.
     *
     * @generated from rpc koloney.application.v1.ApplicationService.UpdateApplicationStatus
     */
    updateApplicationStatus: {
      name: "UpdateApplicationStatus",
      I: UpdateApplicationStatusRequest,
      O: Application,
      kind: MethodKind.Unary,
    },
  }
} as const;

