// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: v1/proto/user/entities.proto

package user

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	unsafe "unsafe"gle.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserStatus represents the possible states of a user account
type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_STATUS_ACTIVE      UserStatus = 1
	UserStatus_USER_STATUS_SUSPENDED   UserStatus = 2
	UserStatus_USER_STATUS_DELETED     UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_ACTIVE",
		2: "USER_STATUS_SUSPENDED",
		3: "USER_STATUS_DELETED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_ACTIVE":      1,
		"USER_STATUS_SUSPENDED":   2,
		"USER_STATUS_DELETED":     3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_user_entities_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_v1_proto_user_entities_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_user_entities_proto_rawDescGZIP(), []int{0}
}

// User represents a user account in the Koloney system
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the user
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User's email address
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// User's display name
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Hashed password
	PasswordHash string `protobuf:"bytes,4,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	// User's profile picture URL
	AvatarUrl *string `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	// Account status (active, suspended, etc)
	Status UserStatus `protobuf:"varint,6,opt,name=status,proto3,enum=user.UserStatus" json:"status,omitempty"`
	// When the user account was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the user last logged in
	LastLoginAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	// User's preferences/settings
	Preferences   *UserPreferences `protobuf:"bytes,9,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1_proto_user_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_user_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1_proto_user_entities_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

func (x *User) GetPreferences() *UserPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

// UserPreferences contains user-specific settings
type UserPreferences struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email notification preferences
	EmailNotificationsEnabled bool `protobuf:"varint,1,opt,name=email_notifications_enabled,json=emailNotificationsEnabled,proto3" json:"email_notifications_enabled,omitempty"`
	// Preferred language code (e.g., "en-US")
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// Theme preference (light/dark)
	Theme string `protobuf:"bytes,3,opt,name=theme,proto3" json:"theme,omitempty"`
	// Time zone (e.g., "America/New_York")
	Timezone      string `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPreferences) Reset() {
	*x = UserPreferences{}
	mi := &file_v1_proto_user_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferences) ProtoMessage() {}

func (x *UserPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_user_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferences.ProtoReflect.Descriptor instead.
func (*UserPreferences) Descriptor() ([]byte, []int) {
	return file_v1_proto_user_entities_proto_rawDescGZIP(), []int{1}
}

func (x *UserPreferences) GetEmailNotificationsEnabled() bool {
	if x != nil {
		return x.EmailNotificationsEnabled
	}
	return false
}

func (x *UserPreferences) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserPreferences) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *UserPreferences) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

var File_v1_proto_user_entities_proto protoreflect.FileDescriptor

const file_v1_proto_user_entities_proto_rawDesc = "" +
	"\n" +
	"\x1cv1/proto/user/entities.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12#\n" +
	"\rpassword_hash\x18\x04 \x01(\tR\fpasswordHash\x12\"\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tH\x00R\tavatarUrl\x88\x01\x01\x12(\n" +
	"\x06status\x18\x06 \x01(\x0e2\x10.user.UserStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\rlast_login_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vlastLoginAt\x127\n" +
	"\vpreferences\x18\t \x01(\v2\x15.user.UserPreferencesR\vpreferencesB\r\n" +
	"\v_avatar_url\"\x9f\x01\n" +
	"\x0fUserPreferences\x12>\n" +
	"\x1bemail_notifications_enabled\x18\x01 \x01(\bR\x19emailNotificationsEnabled\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x14\n" +
	"\x05theme\x18\x03 \x01(\tR\x05theme\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone*u\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15USER_STATUS_SUSPENDED\x10\x02\x12\x17\n" +
	"\x13USER_STATUS_DELETED\x10\x03Bm\n" +
	"\bcom.userB\rEntitiesProtoP\x01Z\"koloney-protos/v1/go/v1/proto/user\xa2\x02\x03UXX\xaa\x02\x04User\xca\x02\x04User\xe2\x02\x10User\\GPBMetadata\xea\x02\x04Userb\x06proto3"

var (
	file_v1_proto_user_entities_proto_rawDescOnce sync.Once
	file_v1_proto_user_entities_proto_rawDescData []byte
)

func file_v1_proto_user_entities_proto_rawDescGZIP() []byte {
	file_v1_proto_user_entities_proto_rawDescOnce.Do(func() {
		file_v1_proto_user_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_proto_user_entities_proto_rawDesc), len(file_v1_proto_user_entities_proto_rawDesc)))
	})
	return file_v1_proto_user_entities_proto_rawDescData
}

var file_v1_proto_user_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_proto_user_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_proto_user_entities_proto_goTypes = []any{
	(UserStatus)(0),               // 0: user.UserStatus
	(*User)(nil),                  // 1: user.User
	(*UserPreferences)(nil),       // 2: user.UserPreferences
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_v1_proto_user_entities_proto_depIdxs = []int32{
	0, // 0: user.User.status:type_name -> user.UserStatus
	3, // 1: user.User.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: user.User.last_login_at:type_name -> google.protobuf.Timestamp
	2, // 3: user.User.preferences:type_name -> user.UserPreferences
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_proto_user_entities_proto_init() }
func file_v1_proto_user_entities_proto_init() {
	if File_v1_proto_user_entities_proto != nil {
		return
	}
	file_v1_proto_user_entities_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_proto_user_entities_proto_rawDesc), len(file_v1_proto_user_entities_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_proto_user_entities_proto_goTypes,
		DependencyIndexes: file_v1_proto_user_entities_proto_depIdxs,
		EnumInfos:         file_v1_proto_user_entities_proto_enumTypes,
		MessageInfos:      file_v1_proto_user_entities_proto_msgTypes,
	}.Build()
	File_v1_proto_user_entities_proto = out.File
	file_v1_proto_user_entities_proto_goTypes = nil
	file_v1_proto_user_entities_proto_depIdxs = nil
}
